In [1]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
df.shape

(569, 31)

In [6]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [7]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
410,11.360,17.57,72.49,399.8,0.08858,0.05313,0.027830,0.02100,0.1601,0.05913,...,13.05,36.32,85.07,521.3,0.14530,0.16220,0.18110,0.08698,0.2973,0.07745
556,10.160,19.59,64.73,311.7,0.10030,0.07504,0.005025,0.01116,0.1791,0.06331,...,10.65,22.88,67.88,347.3,0.12650,0.12000,0.01005,0.02232,0.2262,0.06742
126,13.610,24.69,87.76,572.6,0.09258,0.07862,0.052850,0.03085,0.1761,0.06130,...,16.89,35.64,113.20,848.7,0.14710,0.28840,0.37960,0.13290,0.3470,0.07900
274,17.930,24.48,115.20,998.9,0.08855,0.07027,0.056990,0.04744,0.1538,0.05510,...,20.92,34.69,135.10,1320.0,0.13150,0.18060,0.20800,0.11360,0.2504,0.07948
6,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.112700,0.07400,0.1794,0.05742,...,22.88,27.66,153.20,1606.0,0.14420,0.25760,0.37840,0.19320,0.3063,0.08368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,19.530,32.47,128.00,1223.0,0.08420,0.11300,0.114500,0.06637,0.1428,0.05313,...,27.90,45.41,180.20,2477.0,0.14080,0.40970,0.39950,0.16250,0.2713,0.07568
520,9.295,13.90,59.96,257.8,0.13710,0.12250,0.033320,0.02421,0.2197,0.07696,...,10.57,17.84,67.84,326.6,0.18500,0.20970,0.09996,0.07262,0.3681,0.08982
191,12.770,21.41,82.02,507.4,0.08749,0.06601,0.031120,0.02864,0.1694,0.06287,...,13.75,23.50,89.04,579.5,0.09388,0.08978,0.05186,0.04773,0.2179,0.06871
172,15.460,11.89,102.50,736.9,0.12570,0.15550,0.203200,0.10970,0.1966,0.07069,...,18.79,17.04,125.00,1102.0,0.15310,0.35830,0.58300,0.18270,0.3216,0.10100
421,14.690,13.98,98.22,656.1,0.10310,0.18360,0.145000,0.06300,0.2086,0.07406,...,16.46,18.34,114.10,809.2,0.13120,0.36350,0.32190,0.11080,0.2827,0.09208

In [10]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
500,15.040,16.74,98.73,689.4,0.09883,0.13640,0.07721,0.06142,0.1668,0.06869,...,16.760,20.43,109.70,856.9,0.1135,0.21760,0.18560,0.10180,0.2177,0.08549
534,10.960,17.62,70.79,365.6,0.09687,0.09752,0.05263,0.02788,0.1619,0.06408,...,11.620,26.51,76.43,407.5,0.1428,0.25100,0.21230,0.09861,0.2289,0.08278
314,8.597,18.60,54.09,221.2,0.10740,0.05847,0.00000,0.00000,0.2163,0.07359,...,8.952,22.44,56.65,240.1,0.1347,0.07767,0.00000,0.00000,0.3142,0.08116
404,12.340,14.95,78.29,469.1,0.08682,0.04571,0.02109,0.02054,0.1571,0.05708,...,13.180,16.85,84.11,533.1,0.1048,0.06744,0.04921,0.04793,0.2298,0.05974
204,12.470,18.60,81.09,481.9,0.09965,0.10580,0.08005,0.03821,0.1925,0.06373,...,14.970,24.64,96.05,677.9,0.1426,0.23780,0.26710,0.10150,0.3014,0.08750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,20.130,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.1166,0.19220,0.32150,0.16280,0.2572,0.06637
216,11.890,18.35,77.32,432.2,0.09363,0.11540,0.06636,0.03142,0.1967,0.06314,...,13.250,27.10,86.20,531.2,0.1405,0.30460,0.28060,0.11380,0.3397,0.08365
472,14.920,14.93,96.45,686.9,0.08098,0.08549,0.05539,0.03221,0.1687,0.05669,...,17.180,18.22,112.00,906.6,0.1065,0.27910,0.31510,0.11470,0.2688,0.08273
304,11.460,18.16,73.59,403.1,0.08853,0.07694,0.03344,0.01502,0.1411,0.06243,...,12.680,21.61,82.69,489.8,0.1144,0.17890,0.12260,0.05509,0.2208,0.07638
559,11.510,23.93,74.52,403.5,0.09261,0.10210,0.11120,0.04105,0.1388,0.06570,...,12.480,37.16,82.28,474.2,0.1298,0.25170,0.36300,0.09653,0.2112,0.08732

Scaling

In [11]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [12]:
x_train_scaled

array([[-0.78054869, -0.40589796, -0.79673896, ..., -0.41028947,
         0.08992554, -0.37041933],
       [-1.11906237,  0.05998547, -1.11379771, ..., -1.39244656,
        -1.04318036, -0.92419598],
       [-0.14583554,  1.23622581, -0.17283599, ...,  0.28721523,
         0.88198409, -0.28484068],
       ...,
       [-0.38279511,  0.47974183, -0.4073614 , ..., -1.00647979,
        -1.17545574, -0.85297246],
       [ 0.37603972, -1.71590681,  0.4294122 , ...,  1.04365542,
         0.47718958,  0.92982397],
       [ 0.15882677, -1.2338789 ,  0.25453959, ..., -0.0484741 ,
        -0.14275162,  0.43733266]], shape=(455, 30))

In [13]:
x_test_scaled

array([[ 0.25755993, -0.59732531,  0.27537721, ..., -0.18518016,
        -1.17864309,  0.07348539],
       [-0.89338658, -0.39436619, -0.86619771, ..., -0.23363486,
        -1.00015102, -0.07613921],
       [-1.55997644, -0.16834354, -1.54852774, ..., -1.73147759,
         0.35925732, -0.1655827 ],
       ...,
       [ 0.22370856, -1.01477531,  0.18222078, ...,  0.01076519,
        -0.36427303, -0.07889981],
       [-0.75233921, -0.2698231 , -0.75179506, ..., -0.89468461,
        -1.12923904, -0.4294962 ],
       [-0.73823448,  1.06094294, -0.71379705, ..., -0.26522915,
        -1.28223224,  0.1745234 ]], shape=(114, 30))

In [14]:
y_train

410    B
556    B
126    M
274    M
6      M
      ..
219    M
520    B
191    B
172    M
421    B
Name: diagnosis, Length: 455, dtype: object

In [15]:
y_test

500    B
534    B
314    B
404    B
204    B
      ..
565    M
216    B
472    B
304    B
559    B
Name: diagnosis, Length: 114, dtype: object

Encoding

In [16]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [17]:
y_train_encoded

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])

In [18]:
y_test_encoded

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0])

In [19]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [20]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [21]:
x_train_tensor.shape[1]

30

In [22]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [23]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 50

In [24]:
# defining the model

class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [25]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [26]:
import time
for epoch in range(epochs):
    y_prep = model.forward_pass(x_train_tensor)
    loss = model.loss_function(y_train_tensor)
    print("epoch: ", epoch, "====> loss", loss)
    new_weight = model.backward_propagation(learning_rate)
    time.sleep(0.5)

epoch:  0 ====> loss 0.34960175212670486
epoch:  1 ====> loss 0.3402653568366794
epoch:  2 ====> loss 0.331210322823512
epoch:  3 ====> loss 0.3224268813502181
epoch:  4 ====> loss 0.3139039175938302
epoch:  5 ====> loss 0.30562966678766607
epoch:  6 ====> loss 0.29759241797232716
epoch:  7 ====> loss 0.2897811072966749
epoch:  8 ====> loss 0.2821857397644905
epoch:  9 ====> loss 0.2747976305282461
epoch:  10 ====> loss 0.26760949046055815
epoch:  11 ====> loss 0.2606153944364567
epoch:  12 ====> loss 0.2538106707245936
epoch:  13 ====> loss 0.24719174300188854
epoch:  14 ====> loss 0.24075594783464713
epoch:  15 ====> loss 0.23450134272358622
epoch:  16 ====> loss 0.22842651407048817
epoch:  17 ====> loss 0.22253039068468614
epoch:  18 ====> loss 0.21681206640219872
epoch:  19 ====> loss 0.21127063460762224
epoch:  20 ====> loss 0.20590503752760303
epoch:  21 ====> loss 0.20071393372426832
epoch:  22 ====> loss 0.19569558785077953
epoch:  23 ====> loss 0.19084778701890995
epoch:  24 ====> loss 0.18616778769875467
epoch:  25 ====> loss 0.18165229573598626
epoch:  26 ====> loss 0.1772974799251963
epoch:  27 ====> loss 0.17309901700105593
epoch:  28 ====> loss 0.1690521634602868
epoch:  29 ====> loss 0.1651518478432805
epoch:  30 ====> loss 0.16139277632094673
epoch:  31 ====> loss 0.1577695446974887
epoch:  32 ====> loss 0.1542767510419586
epoch:  33 ====> loss 0.15090910474002106
epoch:  34 ====> loss 0.1476615294272235
epoch:  35 ====> loss 0.14452925870384584
epoch:  36 ====> loss 0.14150792450953928
epoch:  37 ====> loss 0.13859363840019553
epoch:  38 ====> loss 0.13578306560615905
epoch:  39 ====> loss 0.13307349055838094
epoch:  40 ====> loss 0.13046287046701477
epoch:  41 ====> loss 0.12794987053748547
epoch:  42 ====> loss 0.12553387077096062
epoch:  43 ====> loss 0.12321493075572258
epoch:  44 ====> loss 0.12099369685957538
epoch:  45 ====> loss 0.11887123796644702
epoch:  46 ====> loss 0.11684880377276616
epoch:  47 ====> loss 0.11492751495683437
epoch:  48 ====> loss 0.11310801545494702
epoch:  49 ====> loss 0.11139013737598348

In [27]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

0.16801492239248716

In [28]:
y_pred

tensor([3.6990e-02, 2.4538e-03, 7.9164e-04, 7.6208e-05, 1.0698e-01, 9.9764e-01,
        2.5019e-01, 9.7499e-01, 3.6829e-02, 4.1972e-05, 9.9677e-01, 1.0000e+00,
        3.9224e-04, 2.1291e-06, 4.5945e-02, 1.0546e-02, 1.3068e-03, 3.1948e-04,
        4.7316e-01, 3.5725e-04, 1.0000e+00, 7.6118e-04, 8.0759e-01, 1.2196e-01,
        1.0000e+00, 1.4975e-05, 1.0366e-02, 8.6871e-01, 1.0000e+00, 3.4768e-05,
        9.9891e-01, 1.4672e-03, 1.7184e-02, 1.0943e-04, 1.4341e-04, 1.1315e-04,
        3.2124e-05, 9.9708e-01, 9.9859e-01, 3.1670e-03, 9.6798e-01, 2.2753e-01,
        5.0163e-02, 9.9936e-01, 3.8196e-05, 8.6274e-04, 4.0129e-01, 1.0000e+00,
        1.0000e+00, 1.8311e-01, 6.6674e-01, 6.7083e-05, 9.9965e-01, 1.0219e-01,
        4.8910e-02, 9.9073e-01, 1.1957e-02, 3.2879e-05, 1.9494e-04, 8.9497e-02,
        7.5400e-04, 1.0000e+00, 9.9996e-01, 1.0000e+00, 9.9705e-01, 9.9999e-01,
        8.2489e-05, 6.9624e-05, 9.2230e-01, 9.9916e-01, 2.5332e-04, 5.8469e-04,
        1.0000e+00, 2.1449e-02, 6.0326e-01, 2.0046e-01, 6.7263e-02, 1.0059e-02,
        9.9978e-01, 8.9372e-01, 1.0000e+00, 9.7218e-01, 7.7893e-01, 6.5034e-03,
        3.1518e-04, 9.9828e-01, 8.8409e-01, 1.0521e-03, 9.6518e-01, 3.3731e-02,
        9.9952e-01, 7.7464e-02, 1.4666e-03, 9.9988e-01, 9.9957e-01, 7.9734e-04,
        4.9764e-05, 7.4294e-01, 5.6603e-02, 5.1257e-04, 2.3481e-02, 5.3200e-05,
        4.3864e-04, 9.9996e-01, 8.6824e-03, 8.3711e-01, 9.9993e-01, 1.0000e+00,
        5.2859e-01, 1.0000e+00, 1.5919e-01, 1.7510e-02, 4.0416e-04, 2.3721e-01],
       dtype=torch.float64, grad_fn=<ViewBackward0>)

In [29]:
y_test_tensor

tensor([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 0.], dtype=torch.float64)