In [448]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [449]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [450]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [451]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [452]:
df.shape

(569, 31)

In [453]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [454]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [455]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [456]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
51,13.64,16.34,87.21,571.8,0.07685,0.06059,0.01857,0.01723,0.1353,0.05953,...,14.67,23.19,96.08,656.7,0.1089,0.1582,0.1050,0.08586,0.2346,0.08025
496,12.65,18.17,82.69,485.6,0.10760,0.13340,0.08017,0.05074,0.1641,0.06854,...,14.38,22.15,95.29,633.7,0.1533,0.3842,0.3582,0.14070,0.3230,0.10330
344,11.71,15.45,75.03,420.3,0.11500,0.07281,0.04006,0.03250,0.2009,0.06506,...,13.06,18.16,84.16,516.4,0.1460,0.1115,0.1087,0.07864,0.2765,0.07806
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510
499,20.59,21.24,137.80,1320.0,0.10850,0.16440,0.21880,0.11210,0.1848,0.06222,...,23.86,30.76,163.20,1760.0,0.1464,0.3597,0.5179,0.21130,0.2480,0.08999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,17.29,22.13,114.40,947.8,0.08999,0.12730,0.09697,0.07507,0.2108,0.05464,...,20.39,27.24,137.90,1295.0,0.1134,0.2867,0.2298,0.15280,0.3067,0.07484
372,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,0.1973,0.06183,...,22.69,21.84,152.10,1535.0,0.1192,0.2840,0.4024,0.19660,0.2730,0.08666
261,17.35,23.06,111.00,933.1,0.08662,0.06290,0.02891,0.02837,0.1564,0.05307,...,19.85,31.47,128.20,1218.0,0.1240,0.1486,0.1211,0.08235,0.2452,0.06515
331,12.98,19.35,84.52,514.0,0.09579,0.11250,0.07107,0.02950,0.1761,0.06540,...,14.42,21.95,99.21,634.3,0.1288,0.3253,0.3439,0.09858,0.3596,0.09166
26,14.58,21.53,97.41,644.8,0.10540,0.18680,0.14250,0.08783,0.2252,0.06924,...,17.62,33.21,122.40,896.9,0.1525,0.6643,0.5539,0.27010,0.4264,0.12750

In [457]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
374,13.690,16.07,87.84,579.1,0.08302,0.06374,0.025560,0.020310,0.1872,0.05669,...,14.84,20.21,99.16,670.6,0.11050,0.20960,0.13460,0.06987,0.3323,0.07701
476,14.200,20.53,92.41,618.4,0.08931,0.11080,0.050630,0.030580,0.1506,0.06009,...,16.45,27.26,112.10,828.5,0.11530,0.34290,0.25120,0.13390,0.2534,0.07858
55,11.520,18.75,73.34,409.0,0.09524,0.05473,0.030360,0.022780,0.1920,0.05907,...,12.84,22.47,81.81,506.2,0.12490,0.08720,0.09076,0.06316,0.3306,0.07036
97,9.787,19.94,62.11,294.5,0.10240,0.05301,0.006829,0.007937,0.1350,0.06890,...,10.92,26.29,68.81,366.1,0.13160,0.09473,0.02049,0.02381,0.1934,0.08988
0,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.300100,0.147100,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.71190,0.26540,0.4601,0.11890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,11.040,14.93,70.67,372.7,0.07987,0.07079,0.035460,0.020740,0.2003,0.06246,...,12.09,20.83,79.73,447.1,0.10950,0.19820,0.15530,0.06754,0.3202,0.07287
119,17.950,20.01,114.20,982.0,0.08402,0.06722,0.072930,0.055960,0.2129,0.05025,...,20.58,27.83,129.20,1261.0,0.10720,0.12020,0.22490,0.11850,0.4882,0.06111
275,11.890,17.36,76.20,435.6,0.12250,0.07210,0.059290,0.074040,0.2015,0.05875,...,12.40,18.99,79.46,472.4,0.13590,0.08368,0.07153,0.08946,0.2220,0.06033
509,15.460,23.95,103.80,731.3,0.11830,0.18700,0.203000,0.085200,0.1807,0.07083,...,17.11,36.33,117.70,909.4,0.17320,0.49670,0.59110,0.21630,0.3013,0.10670
397,12.800,17.46,83.05,508.3,0.08044,0.08895,0.073900,0.040830,0.1574,0.05750,...,13.74,21.06,90.72,591.0,0.09534,0.18120,0.19010,0.08296,0.1988,0.07053

Scaling

In [458]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [459]:
x_train_scaled

array([[-0.14065485, -0.70503431, -0.1976451 , ..., -0.44124844,
        -0.90604769, -0.21156579],
       [-0.4159101 , -0.25719413, -0.37968175, ...,  0.38240737,
         0.55980098,  1.05321855],
       [-0.67726357, -0.92283636, -0.68817749, ..., -0.54968745,
        -0.21126195, -0.33173402],
       ...,
       [ 0.89085724,  0.93949355,  0.76046373, ..., -0.49396602,
        -0.7302785 , -1.04012299],
       [-0.32415835,  0.03157713, -0.30598107, ..., -0.25020355,
         1.16670213,  0.41451618],
       [ 0.12069862,  0.5650698 ,  0.21314557, ...,  2.32589865,
         2.27437963,  2.38110493]], shape=(455, 30))

In [460]:
x_test_scaled

array([[-0.12675307, -0.77110909, -0.17227274, ..., -0.68140629,
         0.71401357, -0.38934892],
       [ 0.01504509,  0.32034839,  0.01177759, ...,  0.28027645,
        -0.59430612, -0.30320092],
       [-0.73009033, -0.11525572, -0.75623987, ..., -0.78218548,
         0.68582417, -0.75424332],
       ...,
       [-0.62721716, -0.45541847, -0.64105739, ..., -0.38717913,
        -1.11498087, -1.30460284],
       [ 0.36536995,  1.15729561,  0.47049384, ...,  1.51786286,
         0.19997161,  1.2397811 ],
       [-0.37420476, -0.43094633, -0.36518326, ..., -0.48480428,
        -1.49968323, -0.74491519]], shape=(114, 30))

In [461]:
y_train

51     B
496    B
344    B
7      M
499    M
      ..
262    M
372    M
261    M
331    B
26     M
Name: diagnosis, Length: 455, dtype: object

In [462]:
y_test

374    B
476    B
55     B
97     B
0      M
      ..
381    B
119    M
275    B
509    M
397    B
Name: diagnosis, Length: 114, dtype: object

Encoding

In [463]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [464]:
y_train_encoded

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1])

In [465]:
y_test_encoded

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0])

In [466]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [467]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [468]:
x_train_tensor.shape[1]

30

In [469]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [656]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 50

In [664]:
# defining the model

class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [662]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [670]:
import time
for epoch in range(epochs):
    y_prep = model.forward_pass(x_train_tensor)
    loss = model.loss_function(y_train_tensor)
    print("epoch: ", epoch, "====> loss", loss)
    new_weight = model.backward_propagation(learning_rate)
    # time.sleep(1)

epoch:  0 ====> loss 0.12928792641002446
epoch:  1 ====> loss 0.12757687803008264
epoch:  2 ====> loss 0.1259559892465935
epoch:  3 ====> loss 0.12442469152126037
epoch:  4 ====> loss 0.12298177738013115
epoch:  5 ====> loss 0.12162527073179906
epoch:  6 ====> loss 0.12035238324911066
epoch:  7 ====> loss 0.11915956118989576
epoch:  8 ====> loss 0.1180426092547228
epoch:  9 ====> loss 0.11699686510945433
epoch:  10 ====> loss 0.11601739350952457
epoch:  11 ====> loss 0.1150991723262999
epoch:  12 ====> loss 0.11423725119192149
epoch:  13 ====> loss 0.11342687319656541
epoch:  14 ====> loss 0.11266355827133145
epoch:  15 ====> loss 0.1119431523024032
epoch:  16 ====> loss 0.11126184866375619
epoch:  17 ====> loss 0.11061618941748813
epoch:  18 ====> loss 0.11000305274975052
epoch:  19 ====> loss 0.10941963197551097
epoch:  20 ====> loss 0.10886341010940515
epoch:  21 ====> loss 0.10833213280370535
epoch:  22 ====> loss 0.10782378149186465
epoch:  23 ====> loss 0.10733654785605232
epoch:  24 ====> loss 0.10686881022825637
epoch:  25 ====> loss 0.1064191121925867
epoch:  26 ====> loss 0.10598614343811319
epoch:  27 ====> loss 0.1055687227805336
epoch:  28 ====> loss 0.10516578319905696
epoch:  29 ====> loss 0.1047763587015226
epoch:  30 ====> loss 0.10439957282150501
epoch:  31 ====> loss 0.10403462855617274
epoch:  32 ====> loss 0.10368079956650827
epoch:  33 ====> loss 0.10333742247804281
epoch:  34 ====> loss 0.10300389013796828
epoch:  35 ====> loss 0.10267964570187513
epoch:  36 ====> loss 0.10236417743961816
epoch:  37 ====> loss 0.10205701416454256
epoch:  38 ====> loss 0.10175772120339005
epoch:  39 ====> loss 0.10146589683566903
epoch:  40 ====> loss 0.10118116914122151
epoch:  41 ====> loss 0.10090319320329584
epoch:  42 ====> loss 0.10063164862179874
epoch:  43 ====> loss 0.10036623729770076
epoch:  44 ====> loss 0.10010668145495707
epoch:  45 ====> loss 0.09985272187090592
epoch:  46 ====> loss 0.09960411629003682
epoch:  47 ====> loss 0.0993606379993787
epoch:  48 ====> loss 0.09912207454663169
epoch:  49 ====> loss 0.09888822658462648

In [671]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

0.06549763771023033

In [672]:
y_pred

tensor([7.1843e-03, 3.6220e-01, 6.7774e-03, 4.6336e-04, 1.0000e+00, 6.4597e-02,
        4.7295e-04, 2.5814e-04, 4.3934e-03, 1.5923e-02, 9.6229e-01, 9.9997e-01,
        7.1092e-01, 9.9999e-01, 9.9956e-01, 6.7767e-03, 1.2011e-02, 5.7982e-03,
        5.1637e-01, 9.9887e-01, 2.2889e-02, 4.8407e-01, 6.9883e-05, 9.9999e-01,
        8.8830e-04, 8.3026e-03, 9.9964e-01, 3.3724e-02, 1.2121e-03, 9.9998e-01,
        3.1963e-02, 2.0418e-03, 5.3663e-03, 2.4970e-03, 1.3143e-01, 3.9132e-02,
        1.1552e-03, 1.4521e-02, 6.9569e-02, 5.7531e-04, 2.6460e-03, 9.9992e-01,
        9.9999e-01, 1.5688e-03, 9.6323e-01, 1.7219e-05, 1.6636e-02, 1.0000e+00,
        1.0000e+00, 1.0417e-04, 1.4560e-02, 9.9986e-01, 1.0000e+00, 9.9999e-01,
        9.9999e-01, 8.1690e-03, 6.3367e-03, 1.0000e+00, 4.1952e-01, 3.9535e-02,
        8.2804e-05, 3.5694e-03, 1.0000e+00, 9.9972e-01, 9.2177e-01, 8.2486e-03,
        5.0621e-03, 1.0889e-02, 1.4696e-02, 2.1786e-02, 8.2608e-03, 3.8513e-03,
        4.8879e-03, 1.2567e-01, 9.6623e-01, 8.3981e-04, 7.6446e-04, 9.9807e-01,
        1.0515e-01, 1.6188e-03, 8.2071e-01, 1.7654e-01, 3.4559e-02, 6.9652e-03,
        3.6981e-02, 1.3508e-03, 5.5367e-05, 2.5935e-03, 9.9092e-01, 9.9997e-01,
        9.7963e-01, 2.4435e-05, 9.9796e-01, 1.1419e-02, 9.9928e-01, 1.6653e-03,
        9.8903e-02, 3.6214e-01, 3.0228e-04, 1.0000e+00, 4.8730e-03, 1.0000e+00,
        6.5116e-01, 4.0738e-01, 9.9929e-01, 1.0000e+00, 9.9280e-01, 5.6698e-02,
        4.2072e-01, 4.2602e-04, 9.9900e-01, 1.8625e-02, 9.9898e-01, 4.5919e-03],
       dtype=torch.float64, grad_fn=<ViewBackward0>)

In [669]:
y_test_tensor

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
        1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0.,
        0., 0., 1., 0., 1., 0.], dtype=torch.float64)