In [19]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

In [20]:
full_df = pd.read_csv("fashion-mnist_test.csv")
full_df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,32,23,14,20,0,0,1,0,0,0
9996,6,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,8,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,8,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9999,1,0,0,0,0,0,0,0,140,119,...,111,95,75,44,1,0,0,0,0,0

In [21]:
df = full_df[0:6000]
df.shape

(6000, 785)

In [22]:
features = df.iloc[:, 1:]
features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5996,0,0,0,0,0,2,37,18,68,162,...,35,29,16,12,0,0,0,0,0,0
5997,0,0,0,0,0,0,0,0,0,0,...,115,81,67,24,0,0,0,0,0,0
5998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5999,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0

In [23]:
labels = df.iloc[:,0]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size= 0.2, random_state=42, shuffle= True)

In [25]:
x_train = x_train/255.0

In [41]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features.to_numpy()).to(torch.float32)
        self.labels = torch.tensor(labels.to_numpy()).to(torch.long)
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [42]:
train_dataset = CustomDataset(x_train, y_train)

In [351]:
test_dataset = CustomDataset(x_test, y_test)

In [43]:
train_dataset.__len__()

4800

In [44]:
train_dataset.__getitem__(4)

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1098,
         0.2627, 0.5647, 0.4784, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0000, 0.4235, 0.0353, 0.0000, 0.1137, 0.3451, 0.5882, 0.7608, 0.8902,
         1.0000, 0.8353, 0.8510, 0.7882, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0392, 0.6235, 0.7098, 0.6588, 0.9490, 0.8196, 0.7804, 0.7451,
         0.7608, 0.7608, 0.7451, 0.7765, 0.6431, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0118, 0.0000, 0.2157, 0.5961, 0.8314, 0.7961, 0.6980, 0.7020, 0.7137,
         0.7373, 0.7961, 0.8314, 0.8118, 0.8000, 0.7804, 0.0078, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0118, 0.0000, 0.3451, 0.6118, 0.8157, 0.8235, 0.7686, 0.8392,
         0.8314, 0.7804, 0.7529, 0.7529, 0.8000, 0.7882, 0.8549, 0.3922, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0039, 0.0000, 0.0000, 0.5451, 0.6471, 0.8157, 0.7804, 0.8118,
         0.8353, 0.8549, 0.8863, 0.8863, 0.8627, 0.7255, 0.7647, 0.8000, 0.7961,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0039, 0.0000, 0.0039, 0.7137, 0.6431, 0.8000, 0.7647,
         0.7490, 0.7961, 0.8039, 0.7529, 0.7020, 0.7176, 0.7804, 0.7765, 0.7647,
         0.8353, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2275, 0.6902, 0.6941, 0.8039,
         0.7373, 0.7451, 0.7137, 0.7255, 0.7137, 0.7647, 0.8196, 0.8392, 0.7804,
         0.6157, 0.8510, 0.2118, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3922, 0.6235, 0.7686,
         0.7804, 0.7333, 0.7373, 0.7255, 0.7608, 0.8314, 0.8392, 0.8196, 0.6941,
         0.6275, 0.6510, 0.8118, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0039, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0118, 0.5725, 0.6784,
         0.7647, 0.7137, 0.7333, 0.7373, 0.7529, 0.7804, 0.8039, 0.7686, 0.7373,
         0.7137, 0.7020, 0.7294, 0.7647, 0.5294, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2706, 0.6510,
         0.7333, 0.7608, 0.7137, 0.7765, 0.8039, 0.7490, 0.7373, 0.7961, 0.8157,
         0.7804, 0.7882, 0.7176, 0.7176, 0.8392, 0.6157, 0.0000, 0.0000, 0.0000,
         0.0078, 0.0039, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0039, 0.5647,
         0.5961, 0.7647, 0.7686, 0.7529, 0.7804, 0.8118, 0.7686, 0.7765, 0.8157,
         0.7961, 0.7647, 0.7882, 0.7765, 0.8353, 0.9059, 0.4941, 0.0039, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0196, 0.0000, 0.0000, 0.2784,
         0.6275, 0.6157, 0.7843, 0.7451, 0.7765, 0.7804, 0.7961, 0.8196, 0.8235,
         0.7882, 0.8392, 0.8235, 0.8549, 0.8118, 0.6392, 0.6431, 0.1294, 0.0000,
         0.0000, 0.0000, 0.0078, 0.0118, 0.0196, 0.0000, 0.0000, 0.0000, 0.2627,
         0.6745, 0.5922, 0.6902, 0.7490, 0.7137, 0.7843, 0.8039, 0.8118, 0.7490,
         0.7882, 0.8824, 0.7765, 0.7255, 0.5961, 0.5020, 0.5255, 0.6431, 0.0235,
         0.0039, 0.0039, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.1765, 0.4941,
         0.5922, 0.5647, 0.6431, 0.7176, 0.7529, 0.7255, 0.8000, 0.7882, 0.7333,
         0.8353, 0.8157, 0.5529, 0.6667, 0.5294, 0.5255, 0.5451, 0.6510, 0.6941,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0980, 0.2667, 0.3922, 0.5255, 0.6078,
         0.6157, 0.5529, 0.6039, 0.5804, 0.6392, 0.7647, 0.7176, 0.7608, 0.7294,
         0.8392, 0.8706, 0.0353, 0.0196, 0.8235, 0.5608, 0.6078, 0.6392, 0.6510,
         0.6235, 0.0000, 0.0000, 0.1216, 0.5373, 0.6392, 0.5608, 0.5882, 0.5922,
         0.5451, 0.5412, 0.6157, 0.6431, 0.6471, 0.6902, 0.6980, 0.8235, 0.7451,
         0.7804, 0.7686, 0.0000, 0.0000, 0.0784, 0.8196, 0.6157, 0.6078, 0.5922,
         0.6431, 0.5412, 0.0000, 0.0078, 0.5176, 0.5529, 0.5569, 0.5804, 0.5765,
         0.5569, 0.5882, 0.6431, 0.6588, 0.6980, 0.7098, 0.6510, 0.6902, 0.6980,
         0.8000, 0.7882, 0.0000, 0.0000, 0.0000, 0.0471, 0.6980, 0.4902, 0.4784,
         0.4902, 0.5725, 0.3922, 0.0000, 0.3725, 0.6902, 0.6510, 0.6784, 0.6824,
         0.6784, 0.6745, 0.6824, 0.6627, 0.6667, 0.6745, 0.6510, 0.6275, 0.7333,
         0.8000, 0.9608, 0.0000, 0.0000, 0.0078, 0.0000, 0.0431, 0.6627, 0.5294,
         0.5020, 0.5059, 0.5922, 0.3333, 0.0000, 0.0549, 0.3529, 0.5569, 0.6431,
         0.7882, 0.8314, 0.8627, 0.9020, 0.8824, 0.8824, 0.8863, 0.8902, 0.9020,
         0.9412, 0.7490, 0.0078, 0.0000, 0.0000, 0.0078, 0.0000, 0.0588, 0.7961,
         0.6118, 0.6941, 0.6275, 0.7373, 0.3137, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.1137, 0.1725, 0.2706, 0.3490, 0.4157, 0.4353, 0.4000,
         0.3176, 0.1490, 0.0000, 0.0000, 0.0000, 0.0078, 0.0039, 0.0000, 0.0000,
         0.4196, 0.3294, 0.3294, 0.2863, 0.3176, 0.1059, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]),
 tensor(9))

In [417]:
class ImageClassificationModel(nn.Module):

    def __init__(self, number_features):        
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(number_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32,10)
        )
        
        # optimization/ gradient descent
        self.optim = torch.optim.SGD(self.model.parameters(), lr=0.1)
    
    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, labels):
        loss_fn = nn.CrossEntropyLoss()
        self.loss = loss_fn(self.y_pred, labels)
        return self.loss.item()

    def optimization(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()

In [418]:
train_dataset.__len__()

4800

In [419]:
x_train.shape

(4800, 784)

In [420]:
model = ImageClassificationModel(x_train.shape[1])

In [421]:
dataloader = DataLoader(train_dataset, batch_size=30, shuffle= True)

In [422]:
# mini-batch gradient descent
# perfor optimization on each mini batch
batch = 0
for features_batch, target_batch in dataloader:
    batch +=1 
    y_pred = model(features_batch)
    print(target_batch)
    loss = model.loss_function(target_batch)
    print(batch)
    print(loss)
    model.optimization()

tensor([9, 3, 9, 1, 8, 0, 7, 4, 6, 4, 1, 4, 1, 3, 1, 4, 9, 4, 5, 9, 4, 3, 5, 4,
        0, 9, 7, 6, 0, 7])
1
2.276423454284668
tensor([9, 2, 8, 6, 7, 6, 1, 6, 5, 5, 6, 0, 0, 3, 9, 3, 6, 1, 3, 1, 7, 0, 0, 4,
        5, 0, 3, 8, 7, 2])
2
2.326632261276245
tensor([6, 5, 7, 0, 2, 1, 2, 5, 8, 6, 7, 4, 3, 8, 0, 6, 1, 9, 5, 0, 7, 9, 2, 3,
        0, 9, 1, 1, 3, 4])
3
2.3194079399108887
tensor([4, 2, 1, 2, 6, 5, 8, 0, 5, 2, 4, 0, 6, 4, 8, 5, 9, 0, 9, 6, 0, 8, 4, 6,
        9, 2, 3, 9, 6, 1])
4
2.2981271743774414
tensor([5, 7, 6, 5, 2, 1, 9, 4, 0, 7, 5, 0, 0, 7, 3, 8, 9, 2, 5, 8, 9, 7, 8, 3,
        3, 7, 5, 6, 1, 1])
5
2.304734468460083
tensor([8, 5, 4, 2, 1, 4, 6, 6, 2, 0, 7, 4, 5, 1, 6, 8, 1, 9, 0, 9, 5, 8, 9, 5,
        7, 1, 8, 4, 5, 0])
6
2.290865898132324
tensor([9, 6, 8, 6, 0, 8, 8, 9, 5, 4, 2, 0, 5, 8, 6, 2, 4, 6, 4, 0, 3, 3, 9, 9,
        7, 8, 5, 7, 4, 9])
7
2.2675156593322754
tensor([0, 4, 7, 8, 0, 5, 7, 7, 8, 0, 4, 8, 8, 0, 6, 2, 5, 9, 1, 3, 9, 5, 7, 8,
        1, 1, 2, 4, 1, 1])
8
2.3153059482574463
tensor([7, 6, 9, 8, 3, 6, 0, 3, 5, 2, 3, 9, 6, 2, 2, 0, 2, 9, 7, 8, 0, 5, 9, 0,
        2, 6, 9, 4, 4, 7])
9
2.2995150089263916
tensor([6, 7, 6, 7, 7, 4, 0, 1, 1, 8, 1, 0, 8, 9, 3, 2, 9, 6, 2, 1, 0, 1, 8, 5,
        5, 5, 8, 8, 8, 5])
10
2.3029229640960693
tensor([4, 7, 5, 2, 6, 6, 6, 6, 0, 0, 7, 2, 1, 5, 7, 4, 0, 1, 3, 7, 1, 3, 5, 5,
        8, 7, 0, 4, 0, 2])
11
2.3295822143554688
tensor([8, 4, 6, 4, 8, 6, 9, 2, 4, 1, 5, 7, 9, 2, 9, 0, 5, 5, 1, 5, 1, 5, 2, 3,
        5, 3, 2, 4, 6, 5])
12
2.2621052265167236
tensor([2, 6, 0, 8, 8, 3, 5, 3, 5, 8, 0, 4, 9, 7, 2, 3, 7, 1, 1, 7, 5, 2, 7, 5,
        6, 8, 0, 3, 0, 2])
13
2.3103418350219727
tensor([8, 7, 5, 1, 4, 9, 5, 2, 1, 6, 2, 0, 4, 9, 4, 7, 8, 0, 3, 6, 9, 6, 9, 5,
        7, 7, 0, 0, 0, 5])
14
2.2873435020446777
tensor([9, 0, 0, 4, 8, 3, 4, 5, 4, 9, 0, 3, 3, 3, 3, 2, 3, 3, 4, 4, 9, 1, 6, 5,
        6, 3, 8, 0, 9, 2])
15
2.2598044872283936
tensor([7, 4, 2, 1, 4, 2, 5, 1, 4, 7, 1, 1, 2, 5, 4, 4, 4, 4, 2, 8, 6, 8, 6, 3,
        8, 6, 8, 2, 2, 9])
16
2.2968828678131104
tensor([5, 5, 1, 7, 1, 4, 4, 5, 5, 1, 5, 4, 7, 6, 0, 7, 7, 7, 8, 4, 1, 9, 9, 4,
        7, 6, 9, 8, 6, 6])
17
2.2651662826538086
tensor([4, 5, 4, 6, 4, 7, 2, 9, 6, 9, 5, 0, 5, 3, 4, 5, 6, 6, 0, 4, 0, 8, 7, 9,
        6, 9, 0, 4, 7, 3])
18
2.2555863857269287
tensor([4, 9, 2, 5, 0, 4, 3, 9, 5, 5, 0, 7, 6, 8, 1, 1, 0, 7, 7, 9, 7, 4, 6, 0,
        8, 5, 6, 4, 1, 8])
19
2.268990993499756
tensor([0, 1, 6, 5, 7, 8, 1, 2, 0, 4, 5, 1, 6, 9, 4, 5, 3, 8, 9, 8, 3, 7, 0, 4,
        0, 1, 1, 0, 7, 0])
20
2.290444850921631
tensor([3, 7, 2, 0, 4, 5, 2, 3, 7, 6, 1, 9, 9, 7, 8, 6, 8, 9, 9, 3, 2, 2, 1, 3,
        4, 8, 8, 0, 0, 0])
21
2.2852015495300293
tensor([8, 3, 0, 4, 4, 3, 1, 4, 6, 2, 1, 5, 9, 1, 4, 1, 4, 2, 3, 5, 2, 2, 0, 7,
        5, 8, 0, 6, 5, 4])
22
2.2806522846221924
tensor([8, 8, 0, 9, 4, 1, 5, 3, 6, 6, 1, 8, 2, 0, 5, 1, 3, 9, 3, 8, 9, 7, 3, 0,
        6, 3, 3, 6, 8, 8])
23
2.269439220428467
tensor([2, 1, 2, 1, 7, 4, 4, 0, 2, 1, 1, 7, 5, 3, 2, 4, 2, 9, 8, 1, 0, 1, 0, 5,
        6, 7, 6, 3, 0, 1])
24
2.318340301513672
tensor([3, 4, 1, 6, 1, 5, 1, 6, 7, 7, 8, 1, 5, 2, 9, 4, 8, 9, 9, 3, 5, 8, 0, 1,
        4, 3, 0, 3, 1, 3])
25
2.2486484050750732
tensor([4, 7, 8, 1, 4, 5, 5, 1, 0, 6, 1, 3, 9, 0, 7, 4, 5, 8, 9, 0, 4, 3, 7, 7,
        4, 6, 1, 6, 1, 4])
26
2.2515249252319336
tensor([3, 3, 3, 3, 4, 4, 9, 0, 5, 7, 9, 7, 0, 1, 4, 1, 2, 4, 4, 6, 4, 0, 1, 0,
        7, 6, 7, 6, 2, 9])
27
2.254270315170288
tensor([8, 7, 7, 1, 8, 0, 6, 7, 1, 6, 1, 8, 5, 9, 7, 9, 8, 0, 2, 1, 4, 6, 2, 4,
        1, 4, 5, 3, 7, 2])
28
2.278552532196045
tensor([9, 5, 8, 4, 5, 9, 6, 4, 4, 7, 7, 2, 9, 8, 9, 4, 6, 3, 4, 7, 8, 9, 2, 6,
        4, 0, 8, 4, 0, 9])
29
2.2174291610717773
tensor([3, 2, 2, 9, 6, 1, 2, 1, 8, 0, 5, 6, 3, 0, 9, 4, 6, 5, 1, 8, 8, 1, 2, 0,
        0, 6, 2, 7, 5, 6])
30
2.288533926010132
tensor([8, 8, 3, 5, 1, 0, 3, 6, 7, 4, 9, 0, 0, 9, 0, 5, 6, 8, 6, 8, 6, 7, 9, 4,
        1, 3, 8, 6, 2, 4])
31
2.2375261783599854
tensor([4, 7, 1, 2, 4, 8, 4, 9, 7, 2, 1, 7, 0, 4, 8, 2, 8, 4, 0, 7, 5, 5, 7, 1,
        9, 5, 6, 0, 2, 1])
32
2.255642890930176
tensor([8, 7, 6, 6, 6, 0, 2, 5, 0, 9, 9, 4, 0, 2, 1, 8, 0, 3, 2, 3, 2, 9, 6, 8,
        6, 8, 0, 0, 6, 6])
33
2.2649683952331543
tensor([9, 8, 5, 7, 3, 6, 3, 3, 8, 5, 7, 3, 4, 3, 4, 7, 0, 5, 9, 7, 2, 3, 6, 1,
        9, 6, 5, 3, 9, 5])
34
2.1970438957214355
tensor([7, 7, 6, 4, 3, 4, 5, 2, 9, 6, 5, 2, 6, 5, 8, 9, 4, 5, 7, 9, 0, 3, 3, 1,
        2, 2, 0, 2, 3, 0])
35
2.228952646255493
tensor([6, 6, 8, 6, 9, 7, 7, 4, 7, 2, 1, 5, 0, 3, 3, 1, 8, 0, 8, 4, 0, 3, 6, 4,
        1, 3, 3, 3, 8, 5])
36
2.227003335952759
tensor([4, 1, 0, 3, 5, 7, 4, 1, 9, 0, 2, 2, 1, 8, 2, 6, 4, 9, 9, 8, 9, 2, 4, 7,
        2, 3, 9, 9, 8, 8])
37
2.1932485103607178
tensor([5, 3, 7, 5, 3, 3, 3, 0, 6, 3, 4, 1, 9, 9, 8, 5, 6, 6, 2, 5, 0, 4, 6, 9,
        7, 8, 5, 6, 3, 7])
38
2.1701130867004395
tensor([2, 8, 3, 5, 9, 3, 7, 8, 0, 4, 2, 7, 7, 0, 8, 3, 6, 1, 7, 2, 7, 6, 4, 4,
        3, 9, 7, 0, 2, 2])
39
2.226079225540161
tensor([5, 2, 2, 2, 3, 0, 8, 5, 6, 5, 1, 8, 8, 6, 1, 4, 3, 6, 6, 4, 2, 6, 2, 5,
        5, 4, 5, 9, 2, 9])
40
2.200054168701172
tensor([1, 2, 0, 3, 7, 6, 6, 5, 8, 8, 4, 6, 0, 2, 4, 5, 0, 5, 0, 7, 3, 4, 4, 8,
        1, 7, 4, 0, 5, 9])
41
2.2041513919830322
tensor([5, 1, 3, 4, 3, 4, 4, 4, 9, 9, 6, 7, 1, 1, 9, 1, 5, 8, 5, 4, 4, 3, 6, 7,
        2, 6, 2, 9, 3, 7])
42
2.125333547592163
tensor([5, 1, 1, 6, 6, 6, 0, 8, 3, 0, 3, 8, 5, 6, 6, 8, 3, 7, 5, 2, 0, 6, 6, 0,
        3, 8, 3, 5, 7, 7])
43
2.1816868782043457
tensor([9, 0, 5, 0, 4, 3, 7, 4, 6, 5, 7, 2, 4, 7, 1, 7, 0, 2, 7, 3, 9, 2, 3, 9,
        0, 8, 1, 8, 8, 2])
44
2.1690032482147217
tensor([3, 0, 9, 5, 3, 1, 9, 6, 4, 1, 4, 6, 6, 4, 1, 4, 0, 1, 4, 1, 6, 3, 6, 6,
        0, 1, 1, 8, 1, 4])
45
2.1329567432403564
tensor([5, 1, 0, 0, 1, 8, 0, 6, 9, 0, 8, 0, 5, 2, 9, 4, 1, 7, 7, 7, 1, 3, 1, 8,
        2, 9, 4, 8, 1, 5])
46
2.15805721282959
tensor([3, 1, 3, 8, 8, 3, 5, 9, 0, 3, 5, 0, 7, 7, 8, 5, 2, 4, 4, 0, 2, 5, 6, 4,
        9, 6, 4, 8, 6, 9])
47
2.0793373584747314
tensor([5, 0, 7, 0, 7, 6, 1, 2, 0, 6, 8, 8, 9, 7, 7, 8, 9, 4, 0, 3, 2, 5, 3, 6,
        0, 7, 2, 9, 5, 8])
48
2.0970921516418457
tensor([7, 2, 3, 3, 7, 3, 2, 6, 4, 9, 4, 3, 7, 0, 6, 6, 2, 4, 3, 9, 2, 1, 7, 8,
        4, 7, 1, 0, 9, 0])
49
2.0843214988708496
tensor([4, 1, 6, 4, 9, 7, 2, 9, 7, 4, 5, 7, 8, 5, 9, 0, 3, 9, 8, 5, 0, 7, 4, 2,
        0, 1, 8, 0, 0, 8])
50
2.042058229446411
tensor([8, 8, 4, 1, 5, 6, 9, 2, 1, 1, 0, 4, 7, 3, 5, 9, 4, 0, 1, 3, 5, 7, 0, 3,
        1, 2, 9, 0, 5, 7])
51
2.002828359603882
tensor([0, 5, 3, 0, 6, 3, 7, 1, 3, 0, 6, 8, 0, 4, 4, 5, 9, 5, 3, 3, 9, 6, 6, 4,
        1, 4, 7, 6, 8, 5])
52
1.9817249774932861
tensor([4, 8, 4, 3, 7, 3, 9, 0, 0, 9, 4, 1, 6, 7, 4, 0, 2, 0, 1, 6, 7, 4, 1, 5,
        8, 1, 8, 9, 3, 8])
53
1.9899694919586182
tensor([7, 5, 3, 6, 9, 9, 2, 2, 9, 4, 0, 7, 2, 6, 6, 4, 4, 8, 2, 0, 4, 4, 4, 7,
        5, 8, 7, 1, 1, 1])
54
1.9427701234817505
tensor([6, 0, 5, 6, 7, 6, 8, 2, 8, 1, 3, 4, 9, 3, 4, 4, 0, 0, 7, 6, 2, 8, 3, 8,
        6, 7, 1, 1, 8, 7])
55
1.997347116470337
tensor([9, 4, 9, 8, 5, 9, 4, 2, 1, 0, 5, 0, 2, 8, 7, 6, 0, 4, 1, 8, 8, 4, 0, 0,
        5, 7, 8, 3, 3, 2])
56
1.9541409015655518
tensor([8, 6, 3, 0, 9, 3, 2, 5, 3, 0, 1, 5, 4, 3, 5, 5, 3, 6, 2, 2, 0, 9, 8, 3,
        7, 6, 6, 1, 3, 1])
57
1.99192476272583
tensor([9, 9, 7, 7, 6, 0, 1, 0, 9, 1, 5, 5, 5, 2, 4, 3, 8, 5, 2, 0, 7, 7, 1, 9,
        1, 1, 2, 2, 1, 0])
58
1.9797028303146362
tensor([2, 0, 3, 6, 7, 7, 1, 9, 4, 0, 0, 6, 1, 3, 2, 7, 7, 4, 2, 8, 0, 6, 6, 0,
        5, 8, 0, 5, 0, 9])
59
1.8983150720596313
tensor([5, 9, 2, 8, 0, 9, 5, 3, 8, 8, 0, 6, 0, 0, 0, 7, 8, 8, 9, 8, 6, 2, 4, 3,
        6, 8, 9, 6, 6, 6])
60
1.7876018285751343
tensor([6, 0, 8, 3, 9, 2, 8, 6, 1, 3, 4, 3, 0, 0, 2, 3, 0, 9, 7, 2, 1, 1, 1, 0,
        9, 1, 4, 0, 3, 3])
61
1.795159101486206
tensor([8, 2, 2, 5, 9, 1, 2, 0, 4, 8, 3, 0, 7, 1, 5, 3, 2, 6, 0, 1, 7, 3, 2, 0,
        7, 8, 3, 3, 2, 1])
62
1.8599251508712769
tensor([6, 7, 9, 2, 9, 6, 4, 2, 5, 4, 1, 2, 2, 3, 5, 4, 3, 6, 4, 1, 7, 7, 8, 7,
        2, 2, 7, 3, 7, 5])
63
1.9587806463241577
tensor([5, 4, 4, 0, 9, 3, 2, 2, 4, 3, 9, 3, 8, 5, 7, 5, 9, 2, 5, 2, 0, 0, 6, 1,
        3, 2, 7, 6, 6, 3])
64
1.7073124647140503
tensor([6, 6, 6, 4, 4, 0, 3, 2, 7, 9, 1, 8, 4, 2, 9, 6, 7, 2, 7, 3, 8, 4, 6, 5,
        3, 8, 7, 0, 0, 0])
65
1.8127318620681763
tensor([9, 9, 3, 2, 4, 5, 0, 4, 6, 9, 0, 8, 9, 7, 5, 0, 1, 6, 0, 7, 2, 9, 1, 2,
        1, 8, 7, 0, 9, 5])
66
1.5996884107589722
tensor([0, 2, 3, 6, 6, 9, 4, 1, 4, 6, 5, 0, 7, 6, 7, 3, 3, 5, 3, 9, 9, 5, 6, 4,
        2, 4, 5, 2, 4, 2])
67
1.7241772413253784
tensor([7, 8, 8, 3, 7, 9, 8, 6, 7, 4, 3, 8, 2, 8, 6, 4, 3, 3, 3, 0, 1, 7, 3, 3,
        9, 3, 9, 9, 4, 0])
68
1.5432058572769165
tensor([5, 1, 5, 7, 9, 6, 1, 6, 5, 9, 1, 3, 1, 2, 1, 0, 0, 6, 9, 1, 6, 5, 9, 9,
        0, 8, 1, 6, 1, 6])
69
1.7615504264831543
tensor([2, 1, 6, 3, 4, 0, 5, 6, 6, 0, 6, 1, 9, 3, 6, 1, 1, 7, 4, 6, 9, 4, 7, 9,
        4, 2, 2, 8, 3, 9])
70
1.665444016456604
tensor([8, 7, 4, 3, 1, 6, 9, 9, 7, 6, 8, 5, 7, 6, 4, 8, 2, 5, 8, 2, 7, 6, 9, 9,
        4, 5, 4, 2, 0, 3])
71
1.6756975650787354
tensor([2, 6, 1, 9, 4, 3, 3, 7, 2, 1, 9, 8, 0, 0, 2, 3, 7, 8, 2, 7, 8, 4, 0, 0,
        3, 6, 7, 4, 0, 9])
72
1.818597435951233
tensor([9, 4, 8, 7, 8, 4, 5, 5, 8, 0, 8, 3, 1, 5, 9, 7, 7, 9, 3, 0, 7, 6, 8, 2,
        5, 1, 9, 2, 8, 4])
73
1.5517456531524658
tensor([5, 9, 4, 8, 9, 6, 5, 3, 6, 5, 7, 2, 4, 6, 9, 6, 8, 3, 4, 2, 1, 4, 3, 1,
        4, 3, 7, 7, 6, 9])
74
1.5996918678283691
tensor([3, 8, 3, 5, 4, 6, 8, 3, 2, 0, 3, 4, 9, 1, 9, 8, 0, 9, 6, 2, 1, 0, 1, 1,
        1, 9, 2, 9, 5, 1])
75
1.6121056079864502
tensor([0, 7, 7, 9, 9, 9, 9, 4, 3, 5, 8, 8, 5, 2, 6, 4, 9, 5, 4, 8, 4, 4, 2, 6,
        6, 7, 8, 9, 9, 5])
76
1.4593091011047363
tensor([5, 4, 8, 3, 4, 7, 6, 3, 2, 7, 6, 6, 8, 0, 1, 6, 5, 5, 4, 7, 9, 0, 8, 7,
        6, 4, 0, 8, 9, 1])
77
1.5465725660324097
tensor([4, 7, 3, 7, 8, 4, 7, 6, 4, 0, 4, 2, 0, 5, 6, 6, 1, 8, 4, 7, 4, 0, 4, 0,
        6, 5, 6, 2, 4, 6])
78
1.584053874015808
tensor([2, 1, 8, 8, 2, 9, 5, 8, 8, 1, 2, 2, 5, 1, 7, 7, 3, 7, 0, 3, 8, 1, 4, 2,
        6, 3, 4, 9, 2, 7])
79
1.6834560632705688
tensor([3, 4, 2, 5, 8, 9, 9, 3, 6, 4, 5, 6, 6, 9, 2, 9, 3, 2, 3, 7, 3, 7, 5, 6,
        4, 1, 5, 8, 3, 3])
80
1.6108174324035645
tensor([3, 5, 0, 8, 6, 1, 9, 5, 7, 7, 9, 8, 1, 7, 7, 3, 7, 1, 4, 1, 1, 9, 2, 2,
        7, 8, 6, 5, 9, 9])
81
1.3602421283721924
tensor([7, 0, 3, 1, 1, 4, 2, 8, 7, 8, 2, 0, 7, 8, 2, 6, 8, 1, 9, 4, 1, 4, 4, 3,
        7, 2, 4, 1, 8, 3])
82
1.4661109447479248
tensor([7, 8, 1, 8, 5, 8, 0, 1, 4, 7, 2, 6, 1, 7, 8, 6, 0, 3, 4, 3, 6, 8, 4, 0,
        9, 4, 0, 6, 7, 0])
83
1.5778985023498535
tensor([9, 8, 2, 4, 3, 2, 5, 6, 8, 0, 2, 9, 4, 8, 3, 0, 5, 9, 0, 9, 0, 5, 4, 0,
        4, 5, 2, 4, 1, 6])
84
1.969578504562378
tensor([9, 6, 6, 3, 1, 9, 5, 7, 7, 4, 9, 0, 2, 3, 2, 3, 9, 1, 8, 9, 1, 6, 5, 9,
        6, 5, 6, 8, 2, 5])
85
2.166771411895752
tensor([4, 0, 1, 0, 0, 1, 7, 7, 5, 7, 0, 9, 9, 4, 7, 3, 7, 5, 5, 6, 9, 8, 8, 4,
        2, 6, 5, 6, 1, 9])
86
1.8801480531692505
tensor([1, 8, 0, 8, 3, 8, 8, 9, 1, 6, 0, 2, 5, 6, 6, 8, 5, 5, 6, 0, 9, 0, 5, 5,
        9, 9, 2, 5, 9, 2])
87
1.6215649843215942
tensor([2, 2, 6, 6, 7, 3, 3, 4, 5, 5, 9, 6, 8, 7, 4, 5, 9, 8, 5, 5, 6, 8, 8, 4,
        5, 3, 5, 5, 3, 9])
88
1.5798906087875366
tensor([0, 9, 9, 8, 0, 7, 9, 5, 4, 8, 6, 9, 7, 8, 5, 5, 6, 4, 9, 7, 7, 4, 0, 9,
        0, 3, 4, 2, 1, 9])
89
1.443097710609436
tensor([1, 0, 9, 4, 9, 6, 5, 9, 0, 6, 0, 9, 8, 8, 9, 4, 1, 8, 9, 4, 5, 6, 9, 6,
        3, 3, 2, 0, 8, 5])
90
1.369908094406128
tensor([9, 6, 9, 2, 9, 7, 4, 0, 9, 0, 5, 6, 8, 8, 6, 2, 9, 6, 6, 7, 0, 1, 5, 1,
        7, 6, 6, 9, 8, 4])
91
1.3937866687774658
tensor([9, 4, 3, 1, 6, 9, 7, 2, 0, 5, 5, 8, 5, 7, 6, 5, 3, 9, 4, 7, 6, 5, 7, 4,
        2, 2, 7, 0, 8, 6])
92
1.5964125394821167
tensor([2, 1, 5, 5, 0, 3, 4, 6, 6, 1, 0, 8, 8, 4, 2, 4, 9, 3, 6, 9, 1, 1, 6, 1,
        6, 3, 0, 0, 1, 6])
93
1.574092149734497
tensor([6, 4, 7, 3, 3, 4, 4, 2, 1, 6, 5, 8, 5, 7, 0, 6, 6, 9, 5, 4, 5, 9, 3, 6,
        4, 7, 4, 8, 4, 2])
94
1.5167583227157593
tensor([2, 3, 6, 9, 7, 1, 5, 0, 7, 2, 3, 9, 2, 7, 2, 1, 4, 3, 1, 2, 7, 3, 9, 7,
        7, 7, 9, 5, 0, 3])
95
1.646462321281433
tensor([5, 9, 1, 1, 4, 6, 8, 8, 3, 0, 9, 0, 9, 7, 3, 9, 1, 0, 2, 9, 5, 6, 9, 9,
        1, 8, 5, 6, 4, 8])
96
1.4819940328598022
tensor([1, 5, 7, 2, 3, 5, 6, 4, 3, 7, 6, 3, 9, 1, 5, 2, 0, 9, 8, 1, 0, 2, 4, 8,
        2, 8, 3, 7, 9, 6])
97
1.505224585533142
tensor([2, 8, 4, 1, 0, 2, 4, 9, 9, 4, 0, 1, 6, 5, 6, 2, 5, 1, 1, 9, 8, 1, 6, 9,
        6, 6, 7, 5, 0, 8])
98
1.4972060918807983
tensor([3, 5, 2, 6, 9, 4, 1, 9, 0, 7, 8, 5, 0, 2, 5, 8, 0, 4, 2, 7, 6, 0, 7, 8,
        4, 5, 7, 7, 1, 0])
99
1.4109272956848145
tensor([9, 1, 8, 2, 3, 0, 0, 6, 6, 2, 3, 6, 8, 1, 7, 9, 5, 4, 8, 5, 8, 8, 5, 2,
        6, 9, 5, 5, 1, 7])
100
1.2494850158691406
tensor([6, 8, 7, 7, 5, 4, 2, 5, 2, 2, 6, 9, 6, 5, 2, 1, 1, 5, 9, 9, 5, 3, 4, 6,
        8, 9, 0, 4, 8, 5])
101
1.297558307647705
tensor([7, 3, 9, 3, 5, 6, 7, 3, 4, 1, 0, 3, 0, 3, 2, 1, 5, 1, 7, 3, 6, 6, 3, 7,
        0, 5, 8, 9, 1, 9])
102
1.4881527423858643
tensor([1, 0, 5, 8, 8, 6, 2, 8, 0, 2, 2, 4, 3, 8, 1, 0, 0, 3, 3, 2, 7, 1, 7, 0,
        5, 0, 0, 0, 3, 6])
103
1.6570770740509033
tensor([9, 5, 6, 8, 4, 2, 6, 3, 4, 8, 7, 0, 0, 1, 8, 9, 9, 9, 1, 2, 8, 7, 3, 5,
        9, 1, 7, 4, 7, 6])
104
1.4531890153884888
tensor([6, 4, 8, 3, 0, 0, 6, 7, 4, 0, 6, 5, 9, 0, 4, 8, 7, 9, 7, 2, 6, 9, 8, 5,
        9, 1, 5, 7, 5, 5])
105
1.3383049964904785
tensor([8, 8, 9, 4, 4, 3, 6, 9, 1, 8, 1, 5, 0, 3, 3, 5, 5, 7, 1, 7, 6, 2, 5, 1,
        0, 0, 6, 4, 1, 2])
106
1.426287055015564
tensor([1, 9, 7, 2, 3, 9, 6, 6, 2, 3, 6, 4, 0, 0, 5, 1, 0, 5, 9, 4, 3, 7, 9, 8,
        1, 2, 4, 0, 8, 2])
107
1.3848057985305786
tensor([2, 4, 7, 6, 3, 6, 7, 3, 1, 3, 9, 7, 3, 6, 0, 5, 3, 7, 4, 0, 9, 8, 2, 6,
        5, 9, 4, 0, 1, 1])
108
1.8384071588516235
tensor([8, 3, 1, 7, 6, 9, 5, 6, 4, 2, 1, 2, 3, 9, 9, 3, 3, 8, 2, 2, 0, 6, 3, 3,
        7, 9, 2, 8, 1, 2])
109
1.6500332355499268
tensor([5, 0, 3, 9, 0, 0, 6, 6, 7, 2, 1, 4, 6, 2, 5, 8, 7, 6, 8, 0, 7, 8, 5, 3,
        3, 0, 0, 5, 5, 9])
110
1.5631747245788574
tensor([9, 2, 1, 4, 0, 5, 2, 5, 8, 2, 3, 6, 8, 4, 3, 5, 5, 8, 3, 7, 2, 8, 6, 6,
        3, 1, 4, 9, 9, 8])
111
1.352027177810669
tensor([7, 5, 9, 4, 4, 1, 2, 3, 2, 7, 8, 4, 0, 0, 6, 7, 4, 5, 9, 6, 9, 5, 7, 6,
        4, 2, 7, 4, 0, 0])
112
1.3571168184280396
tensor([0, 0, 8, 2, 9, 5, 7, 9, 5, 3, 2, 1, 0, 3, 2, 9, 0, 6, 2, 3, 3, 6, 7, 2,
        0, 0, 5, 4, 6, 0])
113
1.4770874977111816
tensor([2, 7, 6, 7, 5, 8, 8, 7, 1, 6, 4, 1, 2, 7, 1, 6, 0, 0, 5, 6, 7, 8, 3, 0,
        7, 2, 2, 2, 4, 4])
114
1.5233551263809204
tensor([1, 8, 0, 3, 2, 6, 0, 3, 9, 7, 7, 9, 4, 3, 3, 6, 3, 4, 8, 9, 9, 2, 6, 1,
        9, 6, 3, 0, 6, 3])
115
1.560989499092102
tensor([7, 0, 0, 5, 4, 8, 4, 4, 4, 9, 6, 6, 6, 6, 5, 1, 7, 2, 2, 1, 3, 4, 7, 1,
        3, 8, 4, 8, 8, 8])
116
1.598002552986145
tensor([1, 4, 0, 0, 5, 5, 0, 3, 5, 8, 8, 9, 4, 4, 5, 0, 2, 8, 3, 8, 8, 7, 3, 2,
        4, 5, 8, 7, 2, 6])
117
1.678528070449829
tensor([4, 8, 4, 7, 2, 9, 8, 8, 3, 5, 0, 9, 5, 9, 0, 6, 4, 2, 4, 6, 2, 3, 7, 7,
        5, 2, 9, 1, 2, 0])
118
1.798608422279358
tensor([7, 2, 6, 9, 5, 1, 4, 4, 9, 3, 2, 6, 5, 3, 4, 9, 0, 8, 3, 3, 4, 1, 2, 5,
        5, 9, 3, 6, 6, 6])
119
1.5342668294906616
tensor([5, 2, 4, 3, 2, 6, 8, 4, 8, 6, 4, 2, 5, 2, 1, 2, 5, 1, 2, 7, 4, 9, 5, 9,
        2, 2, 2, 2, 8, 1])
120
1.232433795928955
tensor([4, 2, 0, 3, 3, 9, 7, 3, 3, 1, 2, 0, 1, 8, 1, 2, 8, 2, 4, 5, 1, 9, 8, 4,
        5, 0, 2, 3, 5, 1])
121
1.362187147140503
tensor([3, 9, 7, 3, 2, 0, 2, 9, 8, 8, 3, 3, 0, 3, 3, 3, 7, 8, 5, 2, 4, 9, 1, 2,
        8, 0, 3, 4, 0, 5])
122
1.1704189777374268
tensor([7, 2, 7, 2, 0, 0, 0, 8, 5, 1, 1, 8, 9, 7, 7, 3, 1, 3, 5, 8, 2, 8, 3, 0,
        5, 1, 3, 0, 9, 0])
123
1.214559555053711
tensor([8, 8, 2, 2, 0, 2, 0, 0, 8, 7, 5, 8, 5, 4, 3, 1, 6, 2, 8, 7, 2, 8, 5, 1,
        3, 3, 6, 2, 7, 3])
124
1.1520040035247803
tensor([8, 3, 5, 8, 2, 6, 7, 8, 5, 1, 4, 2, 8, 6, 8, 3, 6, 9, 7, 9, 2, 2, 0, 4,
        3, 4, 9, 6, 9, 8])
125
1.2986747026443481
tensor([8, 7, 7, 1, 7, 7, 1, 1, 7, 6, 2, 3, 9, 3, 5, 5, 4, 6, 8, 6, 4, 4, 6, 3,
        3, 4, 2, 5, 9, 7])
126
1.1954936981201172
tensor([2, 3, 6, 8, 8, 9, 7, 2, 8, 4, 7, 0, 3, 6, 0, 3, 3, 5, 8, 8, 4, 2, 0, 7,
        3, 1, 5, 3, 3, 5])
127
1.1373347043991089
tensor([7, 3, 2, 4, 7, 3, 7, 1, 3, 4, 0, 5, 2, 7, 6, 1, 2, 4, 1, 4, 5, 9, 2, 1,
        9, 6, 2, 1, 0, 6])
128
1.191293478012085
tensor([1, 1, 9, 3, 5, 8, 9, 7, 9, 0, 3, 5, 8, 2, 3, 1, 7, 2, 2, 3, 9, 6, 7, 4,
        8, 2, 1, 9, 9, 0])
129
1.0506706237792969
tensor([1, 3, 3, 9, 9, 4, 6, 3, 3, 2, 5, 6, 9, 5, 6, 8, 3, 4, 7, 6, 3, 3, 1, 0,
        1, 6, 8, 7, 4, 1])
130
1.281345248222351
tensor([5, 6, 6, 1, 1, 3, 1, 7, 8, 5, 8, 1, 3, 8, 5, 1, 8, 8, 7, 3, 9, 5, 2, 1,
        8, 5, 4, 2, 7, 7])
131
1.073007583618164
tensor([4, 2, 6, 4, 0, 2, 9, 5, 1, 6, 9, 3, 1, 4, 5, 8, 9, 9, 7, 5, 7, 7, 4, 2,
        6, 3, 4, 5, 8, 9])
132
1.6607431173324585
tensor([0, 6, 3, 3, 8, 5, 1, 1, 1, 7, 9, 8, 7, 1, 5, 7, 7, 9, 1, 9, 5, 5, 2, 7,
        2, 5, 7, 1, 4, 6])
133
2.2054481506347656
tensor([1, 1, 0, 7, 1, 5, 4, 6, 9, 9, 4, 4, 0, 2, 9, 8, 4, 4, 1, 1, 0, 8, 0, 2,
        8, 7, 8, 0, 8, 7])
134
1.7555769681930542
tensor([1, 1, 2, 9, 6, 5, 2, 3, 6, 1, 0, 8, 4, 9, 4, 5, 5, 7, 9, 8, 0, 1, 5, 5,
        9, 5, 1, 5, 6, 0])
135
1.2843118906021118
tensor([9, 5, 6, 2, 6, 6, 4, 7, 4, 8, 8, 6, 7, 0, 0, 4, 4, 5, 7, 9, 1, 7, 7, 8,
        5, 1, 8, 9, 0, 0])
136
1.2046138048171997
tensor([8, 7, 9, 9, 1, 9, 7, 8, 8, 4, 7, 3, 0, 7, 7, 9, 9, 2, 7, 6, 7, 9, 6, 7,
        0, 6, 7, 9, 5, 4])
137
0.9024018049240112
tensor([6, 9, 8, 5, 3, 4, 1, 9, 3, 4, 7, 4, 8, 4, 4, 8, 5, 5, 4, 0, 7, 3, 9, 0,
        1, 8, 9, 6, 7, 8])
138
1.1977239847183228
tensor([3, 8, 1, 7, 2, 4, 8, 2, 1, 0, 4, 0, 9, 1, 2, 1, 8, 4, 4, 1, 8, 8, 4, 4,
        4, 2, 5, 1, 7, 0])
139
0.9177493453025818
tensor([6, 1, 4, 1, 3, 8, 9, 4, 3, 2, 2, 2, 8, 4, 9, 2, 9, 3, 4, 3, 5, 2, 5, 2,
        1, 1, 6, 8, 5, 8])
140
1.1429485082626343
tensor([3, 3, 2, 5, 4, 0, 7, 3, 7, 0, 3, 3, 9, 8, 6, 1, 2, 6, 9, 3, 3, 6, 2, 3,
        3, 0, 0, 4, 9, 2])
141
1.217071294784546
tensor([7, 1, 8, 2, 3, 2, 6, 1, 2, 5, 7, 0, 0, 8, 3, 3, 8, 5, 6, 2, 6, 0, 2, 7,
        9, 6, 6, 4, 4, 9])
142
1.3928760290145874
tensor([8, 3, 2, 3, 7, 9, 1, 9, 3, 5, 4, 7, 2, 9, 9, 1, 1, 0, 1, 6, 4, 6, 4, 2,
        5, 8, 8, 9, 7, 1])
143
1.2851861715316772
tensor([4, 8, 8, 3, 6, 9, 5, 6, 6, 3, 0, 1, 7, 4, 1, 6, 0, 1, 8, 3, 2, 0, 3, 6,
        3, 3, 4, 1, 0, 0])
144
1.3518632650375366
tensor([9, 4, 8, 2, 6, 8, 0, 5, 7, 5, 6, 2, 9, 9, 6, 5, 7, 6, 3, 8, 4, 9, 9, 0,
        0, 8, 8, 9, 3, 3])
145
1.0375094413757324
tensor([2, 8, 2, 3, 8, 1, 6, 2, 7, 1, 6, 8, 4, 3, 6, 6, 1, 1, 2, 2, 9, 3, 4, 2,
        7, 8, 5, 7, 4, 3])
146
1.0699063539505005
tensor([3, 8, 4, 9, 0, 4, 4, 9, 5, 4, 4, 4, 5, 0, 5, 9, 6, 8, 0, 8, 2, 9, 6, 7,
        2, 4, 2, 6, 8, 7])
147
1.118033528327942
tensor([4, 3, 3, 5, 6, 5, 7, 9, 0, 3, 6, 7, 9, 5, 9, 2, 1, 4, 1, 3, 0, 3, 5, 5,
        2, 4, 8, 0, 3, 1])
148
1.1218940019607544
tensor([8, 6, 4, 0, 7, 0, 6, 9, 7, 0, 1, 3, 3, 5, 8, 0, 4, 3, 2, 7, 3, 1, 4, 9,
        4, 9, 7, 5, 2, 2])
149
1.0716705322265625
tensor([3, 8, 1, 7, 0, 2, 2, 9, 3, 5, 5, 7, 9, 6, 7, 6, 2, 7, 7, 6, 8, 7, 4, 6,
        9, 0, 8, 5, 9, 8])
150
1.1427463293075562
tensor([0, 3, 1, 7, 8, 5, 2, 4, 4, 9, 5, 9, 2, 5, 9, 8, 9, 2, 4, 5, 3, 1, 4, 9,
        8, 0, 6, 8, 0, 4])
151
1.185576319694519
tensor([1, 0, 0, 7, 3, 3, 6, 6, 3, 2, 2, 7, 0, 6, 4, 4, 4, 3, 8, 9, 5, 8, 2, 3,
        1, 5, 4, 8, 8, 9])
152
1.2361412048339844
tensor([2, 3, 1, 4, 2, 6, 6, 3, 4, 6, 1, 8, 4, 0, 7, 9, 9, 5, 9, 4, 0, 2, 9, 3,
        9, 5, 2, 7, 0, 4])
153
1.2033894062042236
tensor([1, 3, 2, 5, 5, 7, 9, 8, 9, 5, 0, 6, 8, 6, 6, 6, 5, 5, 9, 5, 1, 6, 5, 0,
        5, 6, 5, 1, 7, 3])
154
1.1352423429489136
tensor([5, 8, 1, 2, 5, 8, 6, 3, 0, 9, 1, 4, 6, 2, 9, 3, 5, 3, 9, 2, 4, 7, 2, 7,
        1, 1, 5, 7, 0, 3])
155
1.1690415143966675