In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

In [2]:
full_df = pd.read_csv("fashion-mnist_test.csv")
full_df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,32,23,14,20,0,0,1,0,0,0
9996,6,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,8,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,8,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9999,1,0,0,0,0,0,0,0,140,119,...,111,95,75,44,1,0,0,0,0,0

In [3]:
df = full_df[0:6000]
df.shape

(6000, 785)

In [4]:
features = df.iloc[:, 1:]
features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5996,0,0,0,0,0,2,37,18,68,162,...,35,29,16,12,0,0,0,0,0,0
5997,0,0,0,0,0,0,0,0,0,0,...,115,81,67,24,0,0,0,0,0,0
5998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5999,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0

In [5]:
labels = df.iloc[:,0]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size= 0.2, random_state=42, shuffle= True)

In [7]:
x_train = x_train/255.0

In [8]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features.to_numpy()).to(torch.float32)
        self.labels = torch.tensor(labels.to_numpy()).to(torch.long)
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [9]:
train_dataset = CustomDataset(x_train, y_train)

In [10]:
test_dataset = CustomDataset(x_test, y_test)

In [11]:
train_dataset.__len__()

4800

In [12]:
train_dataset.__getitem__(4)

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1098,
         0.2627, 0.5647, 0.4784, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0000, 0.4235, 0.0353, 0.0000, 0.1137, 0.3451, 0.5882, 0.7608, 0.8902,
         1.0000, 0.8353, 0.8510, 0.7882, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0392, 0.6235, 0.7098, 0.6588, 0.9490, 0.8196, 0.7804, 0.7451,
         0.7608, 0.7608, 0.7451, 0.7765, 0.6431, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0118, 0.0000, 0.2157, 0.5961, 0.8314, 0.7961, 0.6980, 0.7020, 0.7137,
         0.7373, 0.7961, 0.8314, 0.8118, 0.8000, 0.7804, 0.0078, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0118, 0.0000, 0.3451, 0.6118, 0.8157, 0.8235, 0.7686, 0.8392,
         0.8314, 0.7804, 0.7529, 0.7529, 0.8000, 0.7882, 0.8549, 0.3922, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0039, 0.0000, 0.0000, 0.5451, 0.6471, 0.8157, 0.7804, 0.8118,
         0.8353, 0.8549, 0.8863, 0.8863, 0.8627, 0.7255, 0.7647, 0.8000, 0.7961,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0039, 0.0000, 0.0039, 0.7137, 0.6431, 0.8000, 0.7647,
         0.7490, 0.7961, 0.8039, 0.7529, 0.7020, 0.7176, 0.7804, 0.7765, 0.7647,
         0.8353, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2275, 0.6902, 0.6941, 0.8039,
         0.7373, 0.7451, 0.7137, 0.7255, 0.7137, 0.7647, 0.8196, 0.8392, 0.7804,
         0.6157, 0.8510, 0.2118, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3922, 0.6235, 0.7686,
         0.7804, 0.7333, 0.7373, 0.7255, 0.7608, 0.8314, 0.8392, 0.8196, 0.6941,
         0.6275, 0.6510, 0.8118, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0039, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0118, 0.5725, 0.6784,
         0.7647, 0.7137, 0.7333, 0.7373, 0.7529, 0.7804, 0.8039, 0.7686, 0.7373,
         0.7137, 0.7020, 0.7294, 0.7647, 0.5294, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2706, 0.6510,
         0.7333, 0.7608, 0.7137, 0.7765, 0.8039, 0.7490, 0.7373, 0.7961, 0.8157,
         0.7804, 0.7882, 0.7176, 0.7176, 0.8392, 0.6157, 0.0000, 0.0000, 0.0000,
         0.0078, 0.0039, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0039, 0.5647,
         0.5961, 0.7647, 0.7686, 0.7529, 0.7804, 0.8118, 0.7686, 0.7765, 0.8157,
         0.7961, 0.7647, 0.7882, 0.7765, 0.8353, 0.9059, 0.4941, 0.0039, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0196, 0.0000, 0.0000, 0.2784,
         0.6275, 0.6157, 0.7843, 0.7451, 0.7765, 0.7804, 0.7961, 0.8196, 0.8235,
         0.7882, 0.8392, 0.8235, 0.8549, 0.8118, 0.6392, 0.6431, 0.1294, 0.0000,
         0.0000, 0.0000, 0.0078, 0.0118, 0.0196, 0.0000, 0.0000, 0.0000, 0.2627,
         0.6745, 0.5922, 0.6902, 0.7490, 0.7137, 0.7843, 0.8039, 0.8118, 0.7490,
         0.7882, 0.8824, 0.7765, 0.7255, 0.5961, 0.5020, 0.5255, 0.6431, 0.0235,
         0.0039, 0.0039, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.1765, 0.4941,
         0.5922, 0.5647, 0.6431, 0.7176, 0.7529, 0.7255, 0.8000, 0.7882, 0.7333,
         0.8353, 0.8157, 0.5529, 0.6667, 0.5294, 0.5255, 0.5451, 0.6510, 0.6941,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0980, 0.2667, 0.3922, 0.5255, 0.6078,
         0.6157, 0.5529, 0.6039, 0.5804, 0.6392, 0.7647, 0.7176, 0.7608, 0.7294,
         0.8392, 0.8706, 0.0353, 0.0196, 0.8235, 0.5608, 0.6078, 0.6392, 0.6510,
         0.6235, 0.0000, 0.0000, 0.1216, 0.5373, 0.6392, 0.5608, 0.5882, 0.5922,
         0.5451, 0.5412, 0.6157, 0.6431, 0.6471, 0.6902, 0.6980, 0.8235, 0.7451,
         0.7804, 0.7686, 0.0000, 0.0000, 0.0784, 0.8196, 0.6157, 0.6078, 0.5922,
         0.6431, 0.5412, 0.0000, 0.0078, 0.5176, 0.5529, 0.5569, 0.5804, 0.5765,
         0.5569, 0.5882, 0.6431, 0.6588, 0.6980, 0.7098, 0.6510, 0.6902, 0.6980,
         0.8000, 0.7882, 0.0000, 0.0000, 0.0000, 0.0471, 0.6980, 0.4902, 0.4784,
         0.4902, 0.5725, 0.3922, 0.0000, 0.3725, 0.6902, 0.6510, 0.6784, 0.6824,
         0.6784, 0.6745, 0.6824, 0.6627, 0.6667, 0.6745, 0.6510, 0.6275, 0.7333,
         0.8000, 0.9608, 0.0000, 0.0000, 0.0078, 0.0000, 0.0431, 0.6627, 0.5294,
         0.5020, 0.5059, 0.5922, 0.3333, 0.0000, 0.0549, 0.3529, 0.5569, 0.6431,
         0.7882, 0.8314, 0.8627, 0.9020, 0.8824, 0.8824, 0.8863, 0.8902, 0.9020,
         0.9412, 0.7490, 0.0078, 0.0000, 0.0000, 0.0078, 0.0000, 0.0588, 0.7961,
         0.6118, 0.6941, 0.6275, 0.7373, 0.3137, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.1137, 0.1725, 0.2706, 0.3490, 0.4157, 0.4353, 0.4000,
         0.3176, 0.1490, 0.0000, 0.0000, 0.0000, 0.0078, 0.0039, 0.0000, 0.0000,
         0.4196, 0.3294, 0.3294, 0.2863, 0.3176, 0.1059, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]),
 tensor(9))

In [ ]:
class ImageClassificationModel(nn.Module):

    def __init__(self, number_features):        
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(number_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32,10)
        )
        # optimization/ gradient descent
        self.optim = torch.optim.SGD(self.model.parameters(), lr=0.1)
    
    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, labels):
        loss_fn = nn.CrossEntropyLoss()
        self.loss = loss_fn(self.y_pred, labels)
        return self.loss.item()

    def optimization(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()

In [23]:
train_dataset.__len__()

4800

In [24]:
x_train.shape

(4800, 784)

In [25]:
model = ImageClassificationModel(x_train.shape[1])

In [26]:
dataloader = DataLoader(train_dataset, batch_size=32, shuffle= True)
len(dataloader)

150

In [27]:
epochs = 100

In [28]:
# mini-batch gradient descent
# perfor optimization on each mini batch
batch = 0
for epoch in range(epochs) :
    total_loss = 0
    for features_batch, target_batch in dataloader:
        y_pred = model(features_batch)
        loss = model.loss_function(target_batch)
        model.optimization() 
        total_loss = total_loss + loss
    avg_loss = total_loss/len(dataloader)
    print("epoch:", epoch+1)
    print("loss", avg_loss)

epoch: 1
loss 1.758183841307958
epoch: 2
loss 0.9281094272931417
epoch: 3
loss 0.7607028891642889
epoch: 4
loss 0.6584421346584955
epoch: 5
loss 0.6047115489840508
epoch: 6
loss 0.5474104188879331
epoch: 7
loss 0.5121436299880345
epoch: 8
loss 0.4689744457602501
epoch: 9
loss 0.4482157244284948
epoch: 10
loss 0.43407643099625903
epoch: 11
loss 0.41016547843813894
epoch: 12
loss 0.38223856141169865
epoch: 13
loss 0.37110146671533584
epoch: 14
loss 0.3576650856435299
epoch: 15
loss 0.3400053178767363
epoch: 16
loss 0.326556911021471
epoch: 17
loss 0.3182595671216647
epoch: 18
loss 0.30838599110643067
epoch: 19
loss 0.30321503907442093
epoch: 20
loss 0.2916448756059011
epoch: 21
loss 0.288682061607639
epoch: 22
loss 0.2742968411743641
epoch: 23
loss 0.2651471912364165
epoch: 24
loss 0.25578860089182853
epoch: 25
loss 0.26302856087684634
epoch: 26
loss 0.24970564824839434
epoch: 27
loss 0.23807713215549786
epoch: 28
loss 0.23627970735232035
epoch: 29
loss 0.23067469120025635
epoch: 30
loss 0.23256830440213283
epoch: 31
loss 0.2044592863569657
epoch: 32
loss 0.19336446543534597
epoch: 33
loss 0.2065414396673441
epoch: 34
loss 0.2084290858358145
epoch: 35
loss 0.20616982425252597
epoch: 36
loss 0.23637086704373358
epoch: 37
loss 0.19848991925517717
epoch: 38
loss 0.19565264376501243
epoch: 39
loss 0.18786751242975394
epoch: 40
loss 0.20725725958744684
epoch: 41
loss 0.17496859590212505
epoch: 42
loss 0.165754981264472
epoch: 43
loss 0.15328177103151877
epoch: 44
loss 0.17364635242770116
epoch: 45
loss 0.15220549410829942
epoch: 46
loss 0.1458605692659815
epoch: 47
loss 0.15646195913354555
epoch: 48
loss 0.14464653849601747
epoch: 49
loss 0.13591324095303814
epoch: 50
loss 0.1268583504917721
epoch: 51
loss 0.15207046510030825
epoch: 52
loss 0.1375864589897295
epoch: 53
loss 0.12853784517695507
epoch: 54
loss 0.1478914211442073
epoch: 55
loss 0.12272492790594697
epoch: 56
loss 0.13456240757678947
epoch: 57
loss 0.1034950066016366
epoch: 58
loss 0.11426431588983785
epoch: 59
loss 0.10483039506711066
epoch: 60
loss 0.12827327959860366
epoch: 61
loss 0.10162391260887185
epoch: 62
loss 0.10154987726981442
epoch: 63
loss 0.08866852246224881
epoch: 64
loss 0.09956260967068374
epoch: 65
loss 0.1053613505170991
epoch: 66
loss 0.08293128330881397
epoch: 67
loss 0.08127739777167638
epoch: 68
loss 0.0828527264863563
epoch: 69
loss 0.08196662393088142
epoch: 70
loss 0.08004123222393295
epoch: 71
loss 0.11973728199334194
epoch: 72
loss 0.08392552602415283
epoch: 73
loss 0.07366549643687904
epoch: 74
loss 0.12868700484124324
epoch: 75
loss 0.09187534301541746
epoch: 76
loss 0.08993618155596778
epoch: 77
loss 0.08523769400392969
epoch: 78
loss 0.06842997347470373
epoch: 79
loss 0.07032998213583293
epoch: 80
loss 0.09905460970165829
epoch: 81
loss 0.15995923843234777
epoch: 82
loss 0.08900577239692212
epoch: 83
loss 0.0676015776830415
epoch: 84
loss 0.06294340307824314
epoch: 85
loss 0.046470521638790764
epoch: 86
loss 0.0778017054979379
epoch: 87
loss 0.04667583776754327
epoch: 88
loss 0.055865633943273374
epoch: 89
loss 0.04897257395127478
epoch: 90
loss 0.07691877081912632
epoch: 91
loss 0.041471271369373425
epoch: 92
loss 0.06324769262806512
epoch: 93
loss 0.05758372711405779
epoch: 94
loss 0.05032760210490475
epoch: 95
loss 0.05342351507938777
epoch: 96
loss 0.03129105325652442
epoch: 97
loss 0.05836430266421909
epoch: 98
loss 0.148379864768746
epoch: 99
loss 0.07055590518206979
epoch: 100
loss 0.09836968642193825