In [19]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

In [20]:
full_df = pd.read_csv("fashion-mnist_test.csv")
full_df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,32,23,14,20,0,0,1,0,0,0
9996,6,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,8,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,8,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9999,1,0,0,0,0,0,0,0,140,119,...,111,95,75,44,1,0,0,0,0,0

In [21]:
df = full_df[0:6000]
df.shape

(6000, 785)

In [22]:
features = df.iloc[:, 1:]
features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5996,0,0,0,0,0,2,37,18,68,162,...,35,29,16,12,0,0,0,0,0,0
5997,0,0,0,0,0,0,0,0,0,0,...,115,81,67,24,0,0,0,0,0,0
5998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5999,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0

In [23]:
labels = df.iloc[:,0]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size= 0.2, random_state=42, shuffle= True)

In [25]:
x_train = x_train/255.0

In [41]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features.to_numpy()).to(torch.float32)
        self.labels = torch.tensor(labels.to_numpy()).to(torch.long)
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [42]:
train_dataset = CustomDataset(x_train, y_train)

In [351]:
test_dataset = CustomDataset(x_test, y_test)

In [43]:
train_dataset.__len__()

4800

In [44]:
train_dataset.__getitem__(4)

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1098,
         0.2627, 0.5647, 0.4784, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0000, 0.4235, 0.0353, 0.0000, 0.1137, 0.3451, 0.5882, 0.7608, 0.8902,
         1.0000, 0.8353, 0.8510, 0.7882, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0392, 0.6235, 0.7098, 0.6588, 0.9490, 0.8196, 0.7804, 0.7451,
         0.7608, 0.7608, 0.7451, 0.7765, 0.6431, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000,
         0.0118, 0.0000, 0.2157, 0.5961, 0.8314, 0.7961, 0.6980, 0.7020, 0.7137,
         0.7373, 0.7961, 0.8314, 0.8118, 0.8000, 0.7804, 0.0078, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0118, 0.0000, 0.3451, 0.6118, 0.8157, 0.8235, 0.7686, 0.8392,
         0.8314, 0.7804, 0.7529, 0.7529, 0.8000, 0.7882, 0.8549, 0.3922, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0039, 0.0000, 0.0000, 0.5451, 0.6471, 0.8157, 0.7804, 0.8118,
         0.8353, 0.8549, 0.8863, 0.8863, 0.8627, 0.7255, 0.7647, 0.8000, 0.7961,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0039, 0.0000, 0.0039, 0.7137, 0.6431, 0.8000, 0.7647,
         0.7490, 0.7961, 0.8039, 0.7529, 0.7020, 0.7176, 0.7804, 0.7765, 0.7647,
         0.8353, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2275, 0.6902, 0.6941, 0.8039,
         0.7373, 0.7451, 0.7137, 0.7255, 0.7137, 0.7647, 0.8196, 0.8392, 0.7804,
         0.6157, 0.8510, 0.2118, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3922, 0.6235, 0.7686,
         0.7804, 0.7333, 0.7373, 0.7255, 0.7608, 0.8314, 0.8392, 0.8196, 0.6941,
         0.6275, 0.6510, 0.8118, 0.4941, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039,
         0.0039, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0118, 0.5725, 0.6784,
         0.7647, 0.7137, 0.7333, 0.7373, 0.7529, 0.7804, 0.8039, 0.7686, 0.7373,
         0.7137, 0.7020, 0.7294, 0.7647, 0.5294, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.2706, 0.6510,
         0.7333, 0.7608, 0.7137, 0.7765, 0.8039, 0.7490, 0.7373, 0.7961, 0.8157,
         0.7804, 0.7882, 0.7176, 0.7176, 0.8392, 0.6157, 0.0000, 0.0000, 0.0000,
         0.0078, 0.0039, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0039, 0.5647,
         0.5961, 0.7647, 0.7686, 0.7529, 0.7804, 0.8118, 0.7686, 0.7765, 0.8157,
         0.7961, 0.7647, 0.7882, 0.7765, 0.8353, 0.9059, 0.4941, 0.0039, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0196, 0.0000, 0.0000, 0.2784,
         0.6275, 0.6157, 0.7843, 0.7451, 0.7765, 0.7804, 0.7961, 0.8196, 0.8235,
         0.7882, 0.8392, 0.8235, 0.8549, 0.8118, 0.6392, 0.6431, 0.1294, 0.0000,
         0.0000, 0.0000, 0.0078, 0.0118, 0.0196, 0.0000, 0.0000, 0.0000, 0.2627,
         0.6745, 0.5922, 0.6902, 0.7490, 0.7137, 0.7843, 0.8039, 0.8118, 0.7490,
         0.7882, 0.8824, 0.7765, 0.7255, 0.5961, 0.5020, 0.5255, 0.6431, 0.0235,
         0.0039, 0.0039, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.1765, 0.4941,
         0.5922, 0.5647, 0.6431, 0.7176, 0.7529, 0.7255, 0.8000, 0.7882, 0.7333,
         0.8353, 0.8157, 0.5529, 0.6667, 0.5294, 0.5255, 0.5451, 0.6510, 0.6941,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0980, 0.2667, 0.3922, 0.5255, 0.6078,
         0.6157, 0.5529, 0.6039, 0.5804, 0.6392, 0.7647, 0.7176, 0.7608, 0.7294,
         0.8392, 0.8706, 0.0353, 0.0196, 0.8235, 0.5608, 0.6078, 0.6392, 0.6510,
         0.6235, 0.0000, 0.0000, 0.1216, 0.5373, 0.6392, 0.5608, 0.5882, 0.5922,
         0.5451, 0.5412, 0.6157, 0.6431, 0.6471, 0.6902, 0.6980, 0.8235, 0.7451,
         0.7804, 0.7686, 0.0000, 0.0000, 0.0784, 0.8196, 0.6157, 0.6078, 0.5922,
         0.6431, 0.5412, 0.0000, 0.0078, 0.5176, 0.5529, 0.5569, 0.5804, 0.5765,
         0.5569, 0.5882, 0.6431, 0.6588, 0.6980, 0.7098, 0.6510, 0.6902, 0.6980,
         0.8000, 0.7882, 0.0000, 0.0000, 0.0000, 0.0471, 0.6980, 0.4902, 0.4784,
         0.4902, 0.5725, 0.3922, 0.0000, 0.3725, 0.6902, 0.6510, 0.6784, 0.6824,
         0.6784, 0.6745, 0.6824, 0.6627, 0.6667, 0.6745, 0.6510, 0.6275, 0.7333,
         0.8000, 0.9608, 0.0000, 0.0000, 0.0078, 0.0000, 0.0431, 0.6627, 0.5294,
         0.5020, 0.5059, 0.5922, 0.3333, 0.0000, 0.0549, 0.3529, 0.5569, 0.6431,
         0.7882, 0.8314, 0.8627, 0.9020, 0.8824, 0.8824, 0.8863, 0.8902, 0.9020,
         0.9412, 0.7490, 0.0078, 0.0000, 0.0000, 0.0078, 0.0000, 0.0588, 0.7961,
         0.6118, 0.6941, 0.6275, 0.7373, 0.3137, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.1137, 0.1725, 0.2706, 0.3490, 0.4157, 0.4353, 0.4000,
         0.3176, 0.1490, 0.0000, 0.0000, 0.0000, 0.0078, 0.0039, 0.0000, 0.0000,
         0.4196, 0.3294, 0.3294, 0.2863, 0.3176, 0.1059, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]),
 tensor(9))

In [345]:
class ImageClassificationModel(nn.Module):

    def __init__(self, number_features):        
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(number_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32,10)
        )
        
        # optimization/ gradient descent
        self.optim = torch.optim.SGD(self.model.parameters(), lr=0.01)
    
    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, labels):
        loss_fn = nn.CrossEntropyLoss()
        self.loss = loss_fn(self.y_pred, labels)
        return self.loss.item()

    def optimization(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()

In [346]:
train_dataset.__len__()

4800

In [347]:
x_train.shape

(4800, 784)

In [348]:
model = ImageClassificationModel(x_train.shape[1])

In [349]:
dataloader = DataLoader(train_dataset, batch_size=25, shuffle= True)

In [350]:
# mini-batch gradient descent
# perfor optimization on each mini batch
batch = 0
for features_batch, target_batch in dataloader:
    batch +=1 
    y_pred = model(features_batch)
    print(target_batch)
    loss = model.loss_function(target_batch)
    print(batch)
    print(loss)
    model.optimization()

tensor([5, 4, 3, 9, 3, 1, 1, 7, 1, 1, 3, 0, 7, 6, 8, 4, 2, 2, 7, 2, 2, 3, 2, 0,
        1])
1
2.299252510070801
tensor([1, 7, 6, 6, 3, 9, 7, 1, 9, 2, 9, 2, 4, 9, 1, 2, 9, 7, 4, 1, 9, 2, 7, 1,
        9])
2
2.28922176361084
tensor([3, 4, 5, 3, 9, 3, 1, 6, 4, 9, 2, 3, 8, 9, 3, 9, 0, 9, 7, 7, 1, 5, 7, 8,
        9])
3
2.332580804824829
tensor([4, 1, 8, 0, 3, 8, 3, 0, 5, 8, 2, 8, 9, 2, 6, 8, 9, 5, 4, 8, 2, 1, 8, 1,
        6])
4
2.3298027515411377
tensor([5, 1, 8, 0, 9, 5, 7, 9, 5, 6, 8, 7, 3, 9, 9, 4, 9, 1, 2, 2, 2, 9, 9, 6,
        6])
5
2.3118090629577637
tensor([0, 9, 3, 5, 5, 5, 0, 6, 0, 9, 9, 9, 0, 6, 2, 0, 6, 4, 9, 7, 1, 0, 5, 4,
        6])
6
2.33280873298645
tensor([0, 6, 0, 8, 5, 1, 8, 1, 5, 4, 8, 7, 1, 5, 4, 8, 3, 6, 3, 2, 1, 2, 9, 4,
        6])
7
2.310213565826416
tensor([8, 6, 0, 5, 6, 4, 6, 5, 6, 9, 5, 2, 9, 6, 5, 0, 0, 0, 5, 5, 2, 1, 0, 3,
        8])
8
2.3208184242248535
tensor([7, 2, 0, 0, 8, 9, 3, 8, 3, 1, 9, 6, 2, 3, 1, 0, 3, 5, 5, 0, 8, 3, 1, 6,
        4])
9
2.342921495437622
tensor([7, 2, 2, 1, 3, 5, 5, 8, 3, 4, 9, 0, 4, 4, 9, 1, 3, 5, 2, 4, 8, 6, 1, 4,
        2])
10
2.3054518699645996
tensor([9, 0, 5, 6, 2, 5, 8, 8, 6, 6, 5, 6, 5, 3, 1, 2, 3, 5, 6, 2, 4, 9, 8, 9,
        8])
11
2.3116860389709473
tensor([5, 6, 8, 7, 4, 8, 8, 8, 9, 0, 9, 6, 6, 8, 0, 8, 4, 3, 8, 8, 5, 4, 6, 5,
        4])
12
2.316657304763794
tensor([0, 8, 9, 8, 5, 0, 4, 5, 5, 7, 3, 7, 0, 2, 3, 5, 2, 0, 6, 2, 0, 0, 0, 5,
        6])
13
2.329003095626831
tensor([9, 4, 2, 6, 5, 6, 1, 6, 6, 2, 0, 0, 3, 0, 5, 0, 5, 0, 3, 6, 8, 4, 9, 5,
        3])
14
2.3258602619171143
tensor([6, 0, 4, 1, 3, 6, 2, 0, 6, 4, 3, 6, 5, 5, 3, 0, 6, 9, 7, 5, 6, 4, 6, 8,
        6])
15
2.2965476512908936
tensor([4, 9, 2, 7, 1, 3, 9, 6, 6, 7, 8, 7, 9, 7, 7, 5, 2, 1, 7, 2, 6, 6, 8, 3,
        8])
16
2.2778327465057373
tensor([2, 2, 0, 8, 0, 3, 9, 5, 9, 1, 9, 6, 4, 0, 1, 0, 4, 4, 8, 6, 7, 6, 8, 2,
        3])
17
2.3183043003082275
tensor([0, 1, 1, 7, 3, 9, 8, 0, 4, 7, 5, 5, 4, 7, 9, 1, 6, 9, 0, 3, 3, 3, 8, 6,
        4])
18
2.3201913833618164
tensor([5, 9, 7, 6, 7, 6, 4, 4, 4, 1, 5, 7, 2, 3, 8, 4, 8, 2, 4, 7, 0, 9, 8, 4,
        4])
19
2.274611711502075
tensor([3, 3, 0, 6, 4, 3, 1, 4, 6, 6, 2, 5, 9, 0, 8, 4, 5, 6, 8, 6, 5, 6, 6, 8,
        1])
20
2.303788423538208
tensor([5, 0, 2, 0, 1, 2, 8, 8, 3, 3, 2, 1, 9, 6, 5, 6, 5, 2, 8, 7, 4, 6, 4, 2,
        0])
21
2.30393385887146
tensor([8, 6, 4, 1, 7, 6, 2, 5, 4, 2, 7, 9, 6, 0, 9, 7, 3, 1, 0, 4, 1, 4, 9, 8,
        2])
22
2.286290407180786
tensor([6, 5, 8, 4, 6, 9, 6, 7, 2, 8, 8, 7, 5, 1, 8, 3, 4, 4, 1, 0, 6, 6, 5, 0,
        5])
23
2.293093681335449
tensor([6, 0, 6, 6, 0, 9, 6, 2, 9, 5, 7, 5, 9, 4, 2, 1, 5, 0, 6, 4, 8, 9, 3, 6,
        3])
24
2.3036551475524902
tensor([0, 5, 7, 8, 9, 5, 4, 0, 4, 7, 6, 4, 0, 7, 3, 1, 9, 8, 6, 4, 8, 3, 8, 9,
        5])
25
2.306828498840332
tensor([1, 4, 7, 8, 1, 1, 1, 5, 4, 8, 8, 0, 3, 3, 9, 8, 3, 7, 6, 3, 3, 5, 0, 1,
        7])
26
2.3257203102111816
tensor([2, 2, 5, 8, 2, 1, 5, 9, 4, 5, 7, 9, 7, 2, 3, 1, 2, 8, 6, 3, 6, 1, 6, 8,
        2])
27
2.2907161712646484
tensor([1, 5, 0, 1, 1, 0, 0, 0, 0, 3, 6, 5, 0, 8, 9, 1, 2, 0, 2, 5, 6, 4, 6, 6,
        7])
28
2.31876277923584
tensor([1, 0, 7, 6, 5, 8, 5, 0, 8, 5, 6, 7, 7, 1, 6, 4, 8, 9, 1, 5, 5, 0, 8, 4,
        2])
29
2.293463706970215
tensor([8, 8, 6, 7, 6, 2, 9, 0, 3, 5, 7, 2, 1, 3, 1, 7, 7, 8, 0, 5, 2, 7, 1, 9,
        8])
30
2.297409772872925
tensor([5, 5, 3, 4, 2, 5, 6, 9, 8, 6, 9, 1, 5, 8, 6, 3, 9, 6, 6, 6, 7, 5, 1, 0,
        8])
31
2.300179958343506
tensor([1, 7, 5, 5, 2, 5, 4, 3, 4, 3, 4, 9, 6, 6, 7, 4, 2, 5, 2, 6, 4, 1, 8, 0,
        1])
32
2.2824769020080566
tensor([2, 5, 5, 7, 6, 1, 0, 9, 6, 6, 6, 6, 3, 7, 6, 9, 1, 0, 8, 7, 0, 9, 1, 6,
        7])
33
2.2823331356048584
tensor([4, 1, 7, 4, 3, 9, 9, 7, 7, 8, 8, 7, 2, 1, 8, 8, 2, 5, 6, 2, 8, 5, 5, 9,
        3])
34
2.2953696250915527
tensor([0, 1, 1, 8, 4, 1, 0, 8, 8, 9, 8, 6, 8, 6, 8, 9, 7, 1, 7, 1, 7, 5, 6, 6,
        5])
35
2.296757459640503
tensor([6, 6, 5, 4, 8, 9, 4, 7, 4, 7, 9, 5, 4, 6, 6, 7, 2, 4, 9, 4, 5, 8, 2, 2,
        9])
36
2.2627391815185547
tensor([9, 9, 9, 4, 0, 7, 1, 9, 6, 3, 1, 0, 7, 9, 9, 3, 4, 5, 7, 7, 4, 7, 2, 5,
        0])
37
2.302194118499756
tensor([9, 5, 8, 6, 2, 8, 2, 4, 0, 7, 0, 4, 0, 5, 0, 7, 3, 6, 8, 8, 2, 6, 4, 0,
        9])
38
2.3085973262786865
tensor([6, 2, 1, 2, 1, 8, 1, 4, 3, 7, 6, 7, 7, 9, 1, 0, 4, 4, 9, 5, 4, 4, 2, 2,
        2])
39
2.271946907043457
tensor([7, 7, 7, 9, 5, 2, 1, 5, 2, 6, 5, 1, 0, 7, 8, 3, 2, 1, 4, 3, 3, 8, 4, 3,
        3])
40
2.3022654056549072
tensor([1, 8, 0, 2, 6, 6, 6, 8, 3, 1, 3, 4, 4, 9, 5, 5, 9, 3, 1, 2, 1, 7, 3, 1,
        7])
41
2.3036136627197266
tensor([7, 9, 4, 8, 3, 4, 8, 9, 3, 1, 3, 1, 2, 2, 3, 4, 1, 6, 5, 1, 6, 8, 4, 6,
        7])
42
2.296048164367676
tensor([3, 2, 0, 7, 3, 7, 4, 6, 1, 7, 0, 4, 6, 7, 7, 4, 1, 1, 9, 8, 6, 1, 9, 5,
        2])
43
2.27996826171875
tensor([5, 3, 9, 5, 8, 1, 6, 1, 8, 9, 6, 2, 7, 1, 4, 3, 3, 5, 3, 6, 7, 5, 3, 7,
        2])
44
2.2985384464263916
tensor([1, 2, 3, 6, 0, 0, 2, 0, 5, 4, 4, 0, 0, 3, 2, 4, 3, 2, 9, 3, 3, 4, 2, 1,
        4])
45
2.323540449142456
tensor([5, 9, 0, 2, 1, 2, 0, 8, 0, 1, 6, 1, 6, 1, 1, 8, 0, 9, 9, 0, 3, 4, 4, 9,
        7])
46
2.3207015991210938
tensor([1, 6, 0, 6, 3, 7, 0, 1, 4, 6, 3, 7, 6, 7, 9, 4, 3, 6, 7, 7, 6, 3, 2, 4,
        5])
47
2.2712416648864746
tensor([1, 6, 5, 6, 4, 7, 3, 3, 3, 6, 0, 2, 9, 6, 8, 8, 4, 9, 9, 6, 7, 0, 0, 4,
        2])
48
2.2990403175354004
tensor([3, 3, 1, 3, 0, 8, 4, 9, 8, 6, 9, 1, 0, 4, 1, 0, 7, 3, 3, 9, 5, 1, 5, 0,
        1])
49
2.3391284942626953
tensor([2, 1, 1, 8, 2, 9, 7, 3, 1, 4, 1, 6, 2, 0, 9, 4, 7, 8, 9, 3, 7, 4, 6, 2,
        7])
50
2.279071569442749
tensor([4, 0, 6, 7, 9, 4, 2, 9, 1, 8, 3, 7, 6, 9, 6, 9, 3, 8, 4, 3, 7, 5, 8, 6,
        0])
51
2.3005497455596924
tensor([4, 4, 2, 2, 1, 1, 4, 0, 5, 9, 5, 6, 7, 1, 9, 3, 4, 6, 1, 2, 8, 3, 0, 8,
        1])
52
2.295602321624756
tensor([8, 9, 0, 0, 6, 8, 5, 9, 9, 9, 0, 2, 6, 5, 3, 3, 6, 4, 4, 5, 9, 0, 2, 3,
        2])
53
2.3282723426818848
tensor([0, 2, 9, 0, 2, 6, 2, 8, 5, 7, 4, 1, 0, 1, 8, 2, 2, 6, 0, 8, 4, 4, 5, 8,
        3])
54
2.3044075965881348
tensor([0, 1, 0, 1, 9, 1, 8, 7, 4, 6, 4, 9, 7, 6, 8, 3, 8, 0, 7, 2, 7, 5, 7, 0,
        7])
55
2.291647434234619
tensor([9, 1, 8, 4, 3, 4, 3, 7, 8, 2, 5, 4, 5, 1, 4, 0, 4, 3, 7, 4, 6, 4, 4, 8,
        6])
56
2.282925605773926
tensor([8, 8, 0, 5, 2, 7, 8, 2, 2, 7, 4, 3, 8, 8, 3, 9, 0, 4, 8, 3, 2, 8, 8, 3,
        1])
57
2.3227615356445312
tensor([4, 9, 3, 9, 8, 0, 7, 6, 8, 8, 8, 6, 1, 7, 0, 9, 3, 4, 6, 1, 9, 3, 8, 6,
        4])
58
2.3074746131896973
tensor([5, 3, 7, 5, 8, 6, 6, 6, 0, 4, 2, 6, 4, 3, 7, 9, 4, 9, 6, 5, 4, 2, 8, 8,
        5])
59
2.2784836292266846
tensor([7, 9, 9, 4, 1, 5, 2, 1, 8, 2, 6, 1, 5, 0, 5, 3, 4, 4, 4, 1, 0, 8, 0, 9,
        8])
60
2.3036506175994873
tensor([9, 4, 9, 6, 4, 8, 3, 7, 0, 8, 1, 3, 5, 4, 3, 5, 3, 2, 7, 1, 0, 5, 9, 9,
        2])
61
2.3136162757873535
tensor([9, 4, 5, 4, 0, 4, 3, 4, 2, 3, 9, 9, 4, 4, 8, 9, 9, 3, 3, 9, 2, 8, 1, 8,
        8])
62
2.3229727745056152
tensor([7, 6, 2, 4, 0, 4, 2, 6, 4, 3, 7, 3, 3, 1, 8, 2, 0, 0, 6, 6, 3, 5, 3, 6,
        5])
63
2.2918615341186523
tensor([1, 4, 5, 0, 3, 5, 5, 7, 8, 9, 6, 5, 8, 7, 0, 0, 0, 7, 2, 4, 2, 1, 0, 6,
        2])
64
2.2982940673828125
tensor([8, 4, 0, 4, 4, 5, 1, 3, 0, 1, 2, 2, 0, 9, 7, 9, 3, 5, 1, 2, 5, 7, 2, 5,
        4])
65
2.294654607772827
tensor([0, 7, 9, 6, 4, 9, 6, 1, 8, 8, 4, 6, 3, 0, 8, 9, 7, 7, 3, 3, 4, 5, 6, 0,
        9])
66
2.303713083267212
tensor([9, 6, 4, 5, 2, 5, 8, 0, 2, 7, 6, 8, 3, 3, 1, 0, 0, 1, 7, 6, 1, 8, 6, 1,
        4])
67
2.296250104904175
tensor([5, 3, 4, 1, 2, 1, 3, 2, 6, 7, 0, 7, 9, 5, 9, 0, 2, 4, 6, 6, 3, 8, 3, 8,
        7])
68
2.297410011291504
tensor([3, 0, 4, 4, 7, 6, 9, 0, 8, 5, 0, 6, 8, 4, 4, 8, 2, 8, 2, 5, 0, 1, 4, 4,
        3])
69
2.2986414432525635
tensor([7, 6, 3, 8, 0, 8, 4, 7, 6, 1, 9, 2, 5, 5, 8, 0, 7, 3, 4, 1, 1, 7, 4, 0,
        3])
70
2.292205333709717
tensor([4, 5, 1, 8, 6, 7, 2, 0, 8, 2, 4, 2, 9, 7, 9, 5, 1, 9, 3, 8, 2, 6, 1, 2,
        6])
71
2.2822089195251465
tensor([2, 2, 0, 4, 8, 9, 0, 6, 7, 5, 9, 5, 4, 3, 0, 9, 6, 4, 2, 4, 6, 9, 9, 4,
        5])
72
2.2913005352020264
tensor([4, 3, 1, 3, 6, 1, 5, 8, 1, 8, 5, 7, 6, 0, 4, 4, 2, 4, 2, 3, 3, 1, 2, 8,
        4])
73
2.290188789367676
tensor([9, 2, 4, 4, 0, 5, 3, 3, 9, 3, 9, 9, 0, 9, 5, 7, 1, 3, 3, 6, 4, 8, 1, 9,
        4])
74
2.3211569786071777
tensor([4, 7, 6, 7, 3, 9, 3, 5, 8, 0, 2, 4, 3, 7, 1, 6, 4, 4, 8, 2, 8, 3, 7, 3,
        9])
75
2.291628360748291
tensor([2, 3, 0, 2, 7, 2, 1, 5, 6, 0, 6, 3, 9, 9, 1, 6, 6, 8, 0, 4, 1, 5, 3, 0,
        7])
76
2.301892042160034
tensor([8, 3, 4, 3, 0, 4, 7, 8, 0, 0, 8, 2, 7, 6, 6, 6, 8, 4, 0, 2, 1, 5, 5, 7,
        9])
77
2.292104959487915
tensor([3, 7, 5, 8, 2, 4, 6, 7, 5, 4, 6, 2, 0, 3, 3, 2, 3, 9, 9, 0, 9, 4, 1, 9,
        4])
78
2.298520565032959
tensor([3, 7, 5, 9, 9, 7, 1, 4, 4, 6, 0, 2, 2, 0, 4, 4, 8, 0, 9, 6, 2, 9, 6, 4,
        3])
79
2.2818069458007812
tensor([4, 7, 9, 2, 7, 7, 0, 9, 9, 0, 8, 3, 1, 8, 3, 4, 1, 3, 8, 6, 9, 4, 5, 7,
        9])
80
2.3014986515045166
tensor([7, 2, 4, 4, 2, 0, 3, 6, 3, 1, 3, 5, 4, 2, 5, 5, 5, 7, 3, 6, 3, 8, 9, 6,
        2])
81
2.2905874252319336
tensor([0, 2, 8, 6, 3, 0, 6, 8, 1, 9, 5, 7, 0, 1, 9, 0, 6, 0, 5, 8, 1, 7, 2, 1,
        9])
82
2.3116841316223145
tensor([0, 9, 1, 8, 7, 4, 4, 0, 9, 1, 9, 0, 2, 0, 7, 8, 7, 7, 2, 6, 1, 8, 6, 2,
        8])
83
2.2878501415252686
tensor([8, 7, 2, 4, 3, 1, 4, 1, 9, 0, 7, 0, 6, 9, 1, 5, 3, 5, 2, 5, 7, 5, 6, 4,
        9])
84
2.288320541381836
tensor([3, 9, 4, 1, 7, 8, 9, 1, 2, 8, 9, 9, 5, 3, 2, 0, 0, 6, 5, 2, 9, 3, 1, 2,
        3])
85
2.3184499740600586
tensor([1, 2, 2, 5, 3, 2, 6, 8, 2, 1, 1, 5, 1, 0, 1, 3, 0, 1, 1, 0, 7, 4, 9, 8,
        9])
86
2.309083938598633
tensor([1, 0, 2, 9, 2, 4, 9, 5, 1, 1, 8, 1, 6, 5, 5, 8, 4, 2, 3, 4, 3, 7, 9, 5,
        7])
87
2.2886972427368164
tensor([6, 7, 1, 9, 2, 8, 3, 7, 5, 6, 5, 5, 3, 4, 2, 6, 9, 2, 8, 0, 1, 8, 0, 7,
        8])
88
2.291131019592285
tensor([4, 3, 2, 9, 0, 8, 9, 2, 9, 3, 7, 6, 4, 4, 2, 4, 9, 2, 1, 5, 1, 8, 0, 0,
        6])
89
2.2899932861328125
tensor([6, 3, 6, 5, 2, 0, 7, 6, 4, 4, 5, 3, 6, 9, 4, 9, 5, 6, 3, 1, 7, 7, 0, 2,
        9])
90
2.2780418395996094
tensor([9, 5, 6, 8, 7, 0, 9, 4, 7, 9, 9, 9, 8, 7, 1, 0, 9, 4, 9, 7, 9, 4, 8, 5,
        4])
91
2.29164981842041
tensor([4, 5, 1, 1, 4, 6, 3, 8, 2, 3, 7, 6, 6, 9, 7, 0, 3, 6, 8, 2, 4, 6, 1, 3,
        9])
92
2.2818033695220947
tensor([1, 5, 3, 0, 8, 8, 1, 1, 4, 4, 3, 6, 8, 8, 5, 5, 3, 7, 8, 8, 2, 0, 2, 5,
        7])
93
2.30652117729187
tensor([5, 3, 4, 0, 5, 4, 3, 3, 7, 2, 7, 0, 1, 7, 5, 6, 2, 0, 5, 5, 3, 7, 2, 2,
        4])
94
2.289555311203003
tensor([9, 4, 8, 7, 9, 7, 1, 4, 9, 4, 2, 6, 7, 4, 3, 3, 8, 6, 9, 3, 6, 0, 5, 2,
        5])
95
2.281491279602051
tensor([8, 2, 3, 5, 9, 1, 1, 1, 3, 0, 0, 2, 1, 9, 8, 9, 1, 2, 7, 7, 6, 8, 8, 0,
        2])
96
2.3080639839172363
tensor([0, 7, 4, 9, 7, 6, 0, 0, 4, 7, 4, 9, 1, 1, 0, 0, 4, 2, 1, 3, 4, 6, 8, 6,
        7])
97
2.2726879119873047
tensor([6, 0, 6, 5, 4, 5, 3, 5, 7, 4, 6, 3, 2, 5, 6, 7, 7, 1, 4, 2, 1, 4, 9, 9,
        4])
98
2.263533353805542
tensor([2, 4, 5, 4, 6, 7, 2, 2, 1, 8, 8, 7, 3, 9, 9, 9, 6, 4, 1, 1, 9, 1, 3, 4,
        5])
99
2.2748711109161377
tensor([7, 0, 9, 7, 3, 9, 2, 6, 9, 6, 8, 7, 9, 6, 6, 0, 1, 3, 8, 1, 1, 7, 8, 9,
        7])
100
2.2874112129211426
tensor([2, 0, 1, 6, 9, 9, 4, 7, 1, 0, 6, 8, 5, 6, 4, 4, 6, 2, 6, 7, 0, 3, 0, 8,
        3])
101
2.286912202835083
tensor([0, 3, 8, 8, 4, 1, 7, 5, 8, 5, 1, 5, 7, 9, 3, 1, 7, 7, 6, 9, 4, 4, 7, 5,
        3])
102
2.2876322269439697
tensor([3, 6, 3, 1, 9, 8, 9, 3, 2, 6, 1, 0, 6, 8, 8, 9, 6, 7, 7, 5, 0, 2, 1, 4,
        8])
103
2.294757843017578
tensor([7, 9, 3, 7, 2, 5, 7, 5, 8, 9, 7, 3, 0, 5, 3, 6, 9, 0, 7, 1, 9, 9, 7, 4,
        9])
104
2.2910959720611572
tensor([0, 5, 4, 0, 5, 3, 6, 8, 2, 7, 2, 4, 1, 7, 9, 8, 6, 3, 2, 1, 0, 1, 7, 4,
        9])
105
2.280108690261841
tensor([5, 0, 4, 5, 6, 8, 5, 8, 5, 2, 0, 6, 3, 8, 3, 1, 0, 6, 9, 3, 5, 0, 9, 4,
        6])
106
2.3134570121765137
tensor([1, 6, 2, 4, 5, 8, 8, 9, 0, 6, 7, 4, 9, 3, 2, 9, 3, 0, 7, 0, 0, 9, 2, 4,
        1])
107
2.294461250305176
tensor([9, 4, 4, 2, 5, 8, 1, 5, 8, 8, 4, 2, 0, 3, 8, 9, 3, 9, 1, 1, 6, 2, 7, 2,
        3])
108
2.296642541885376
tensor([0, 9, 6, 2, 3, 8, 1, 7, 3, 0, 7, 2, 8, 9, 6, 0, 2, 9, 6, 4, 7, 9, 5, 1,
        9])
109
2.2899672985076904
tensor([7, 1, 1, 9, 3, 5, 9, 8, 3, 1, 7, 8, 6, 9, 0, 1, 7, 4, 6, 5, 1, 5, 1, 8,
        4])
110
2.28882098197937
tensor([5, 7, 9, 2, 0, 5, 5, 8, 9, 3, 0, 3, 6, 9, 9, 9, 5, 9, 6, 9, 4, 1, 7, 8,
        9])
111
2.309420347213745
tensor([7, 4, 8, 3, 2, 8, 6, 2, 6, 5, 5, 8, 5, 8, 0, 0, 1, 9, 5, 9, 7, 2, 5, 0,
        9])
112
2.299187660217285
tensor([3, 0, 1, 3, 6, 6, 6, 8, 5, 0, 4, 1, 1, 5, 1, 6, 8, 4, 0, 7, 0, 7, 8, 9,
        5])
113
2.294989824295044
tensor([9, 7, 4, 0, 9, 8, 9, 3, 3, 4, 4, 7, 7, 3, 1, 7, 6, 0, 2, 5, 9, 5, 3, 8,
        4])
114
2.2898054122924805
tensor([2, 4, 5, 3, 8, 1, 7, 3, 1, 3, 6, 1, 6, 6, 8, 6, 5, 8, 0, 2, 1, 4, 6, 7,
        7])
115
2.2753653526306152
tensor([2, 0, 8, 3, 1, 0, 5, 7, 0, 0, 3, 1, 7, 1, 8, 7, 4, 1, 6, 1, 9, 0, 9, 6,
        0])
116
2.300044298171997
tensor([9, 7, 0, 6, 0, 7, 8, 8, 5, 5, 0, 2, 2, 4, 4, 5, 9, 6, 1, 6, 1, 6, 0, 5,
        9])
117
2.2856006622314453
tensor([6, 1, 9, 8, 1, 6, 7, 6, 7, 8, 9, 4, 9, 5, 6, 2, 8, 2, 9, 5, 0, 5, 9, 8,
        1])
118
2.2808051109313965
tensor([8, 4, 9, 7, 7, 4, 8, 1, 8, 9, 6, 6, 9, 8, 2, 4, 6, 2, 9, 8, 1, 5, 7, 0,
        8])
119
2.266122817993164
tensor([6, 5, 2, 2, 9, 3, 1, 6, 7, 4, 3, 3, 3, 4, 1, 5, 8, 0, 4, 2, 3, 7, 8, 9,
        3])
120
2.2998361587524414
tensor([3, 0, 3, 1, 7, 2, 7, 4, 5, 1, 8, 5, 7, 2, 5, 3, 7, 0, 5, 2, 4, 6, 3, 8,
        1])
121
2.2868473529815674
tensor([1, 2, 2, 9, 8, 5, 0, 2, 7, 8, 6, 0, 9, 6, 6, 0, 7, 2, 1, 4, 3, 0, 5, 1,
        6])
122
2.276444911956787
tensor([6, 1, 1, 3, 3, 6, 7, 2, 5, 6, 9, 4, 7, 5, 5, 0, 9, 8, 9, 5, 8, 5, 5, 9,
        5])
123
2.290677547454834
tensor([2, 8, 2, 8, 8, 4, 9, 4, 0, 6, 6, 2, 7, 9, 2, 4, 0, 2, 5, 3, 3, 1, 9, 4,
        7])
124
2.274042844772339
tensor([4, 6, 7, 7, 9, 6, 5, 6, 3, 5, 8, 5, 2, 0, 9, 1, 0, 2, 9, 6, 1, 5, 6, 4,
        3])
125
2.281456470489502
tensor([4, 1, 9, 9, 2, 2, 5, 3, 0, 0, 3, 4, 3, 3, 7, 1, 4, 4, 3, 6, 5, 2, 0, 4,
        4])
126
2.2960240840911865
tensor([4, 9, 5, 9, 4, 2, 7, 2, 8, 4, 7, 6, 2, 3, 5, 8, 3, 8, 5, 6, 0, 3, 4, 9,
        8])
127
2.2831480503082275
tensor([4, 0, 3, 0, 4, 6, 7, 0, 6, 7, 7, 3, 0, 5, 2, 9, 0, 2, 9, 8, 5, 4, 4, 6,
        7])
128
2.27755069732666
tensor([2, 5, 7, 8, 2, 1, 2, 1, 0, 3, 4, 9, 1, 6, 7, 0, 3, 7, 6, 0, 0, 2, 7, 7,
        3])
129
2.276501178741455
tensor([7, 1, 6, 7, 7, 0, 1, 2, 6, 2, 7, 5, 0, 0, 0, 5, 0, 4, 8, 5, 0, 2, 7, 9,
        5])
130
2.277388572692871
tensor([3, 5, 1, 2, 6, 1, 5, 7, 3, 5, 4, 6, 1, 7, 7, 3, 0, 9, 0, 1, 6, 6, 4, 1,
        2])
131
2.272256851196289
tensor([6, 0, 6, 4, 0, 0, 9, 0, 8, 6, 5, 9, 4, 2, 2, 2, 3, 1, 7, 4, 9, 5, 2, 2,
        5])
132
2.2735185623168945
tensor([3, 5, 5, 6, 5, 7, 6, 6, 6, 0, 4, 7, 7, 0, 3, 4, 6, 2, 9, 2, 1, 6, 5, 2,
        0])
133
2.2656455039978027
tensor([9, 7, 3, 5, 5, 0, 8, 6, 9, 0, 8, 4, 6, 6, 5, 8, 7, 0, 3, 4, 0, 4, 3, 5,
        7])
134
2.292205572128296
tensor([3, 3, 8, 0, 7, 8, 1, 1, 3, 5, 7, 9, 1, 0, 0, 4, 2, 1, 0, 0, 6, 5, 8, 9,
        6])
135
2.305929660797119
tensor([5, 1, 5, 7, 8, 1, 8, 2, 9, 2, 3, 2, 4, 7, 4, 3, 2, 8, 9, 7, 0, 7, 8, 1,
        8])
136
2.2784006595611572
tensor([7, 6, 8, 7, 7, 0, 6, 1, 9, 1, 3, 6, 0, 6, 2, 0, 1, 1, 9, 7, 1, 8, 1, 0,
        6])
137
2.273547887802124
tensor([8, 4, 5, 9, 1, 9, 1, 0, 0, 1, 9, 7, 4, 1, 6, 0, 3, 8, 4, 4, 7, 2, 8, 3,
        3])
138
2.2883434295654297
tensor([0, 1, 4, 2, 3, 9, 7, 1, 8, 6, 0, 0, 3, 1, 6, 1, 5, 6, 2, 9, 8, 1, 9, 1,
        0])
139
2.2896385192871094
tensor([6, 1, 6, 5, 3, 8, 4, 5, 6, 0, 7, 6, 7, 4, 6, 9, 5, 2, 0, 6, 4, 4, 3, 6,
        6])
140
2.255631923675537
tensor([3, 7, 6, 2, 8, 9, 2, 4, 5, 4, 7, 3, 4, 6, 0, 9, 1, 2, 6, 1, 5, 7, 0, 8,
        4])
141
2.266211986541748
tensor([4, 3, 5, 8, 4, 8, 1, 5, 3, 7, 3, 8, 8, 9, 5, 6, 4, 4, 5, 2, 3, 1, 6, 3,
        0])
142
2.298999071121216
tensor([8, 9, 7, 8, 3, 5, 5, 6, 3, 4, 3, 7, 4, 0, 4, 8, 0, 3, 1, 9, 0, 3, 0, 3,
        2])
143
2.317556858062744
tensor([6, 3, 3, 8, 2, 3, 9, 0, 6, 4, 3, 4, 6, 9, 4, 8, 4, 5, 2, 0, 0, 1, 8, 3,
        0])
144
2.300567626953125
tensor([1, 3, 7, 7, 9, 7, 9, 7, 4, 4, 3, 4, 8, 2, 6, 7, 1, 5, 6, 6, 1, 6, 6, 8,
        3])
145
2.2527916431427
tensor([4, 9, 8, 0, 7, 7, 9, 3, 7, 2, 0, 8, 9, 9, 8, 6, 0, 5, 0, 7, 6, 4, 3, 6,
        3])
146
2.2838573455810547
tensor([8, 6, 0, 3, 5, 9, 2, 7, 2, 5, 8, 0, 3, 0, 8, 5, 8, 2, 6, 1, 9, 6, 7, 8,
        9])
147
2.292619228363037
tensor([0, 6, 5, 1, 0, 0, 9, 2, 3, 8, 2, 5, 3, 9, 5, 9, 1, 9, 7, 2, 2, 7, 2, 4,
        5])
148
2.2860772609710693
tensor([6, 3, 0, 3, 0, 0, 3, 2, 4, 5, 0, 4, 7, 9, 0, 8, 8, 8, 1, 4, 4, 9, 9, 1,
        5])
149
2.2932732105255127
tensor([8, 4, 4, 5, 3, 8, 8, 0, 8, 8, 7, 4, 2, 6, 9, 9, 8, 1, 2, 5, 3, 4, 6, 5,
        8])
150
2.2853622436523438
tensor([7, 7, 7, 2, 5, 6, 3, 2, 7, 6, 6, 1, 9, 8, 1, 5, 1, 1, 0, 0, 8, 4, 1, 9,
        0])
151
2.2689623832702637
tensor([5, 2, 3, 7, 0, 4, 4, 5, 7, 6, 4, 5, 1, 5, 7, 9, 2, 1, 2, 0, 5, 5, 9, 0,
        7])
152
2.2684166431427
tensor([8, 0, 4, 4, 7, 3, 9, 1, 3, 3, 5, 0, 1, 7, 8, 9, 0, 0, 8, 2, 4, 6, 7, 2,
        5])
153
2.2820136547088623
tensor([3, 4, 8, 3, 5, 5, 9, 3, 5, 7, 0, 2, 7, 8, 8, 9, 9, 2, 3, 8, 8, 4, 5, 9,
        7])
154
2.3065013885498047
tensor([8, 1, 2, 7, 9, 0, 3, 4, 0, 6, 1, 5, 5, 3, 7, 8, 5, 2, 0, 0, 8, 9, 9, 9,
        4])
155
2.293408155441284
tensor([9, 1, 6, 3, 2, 1, 1, 9, 8, 3, 3, 1, 8, 3, 5, 4, 2, 3, 7, 5, 1, 4, 9, 2,
        8])
156
2.2975125312805176
tensor([7, 9, 4, 0, 3, 9, 6, 6, 2, 1, 0, 2, 6, 2, 9, 9, 6, 4, 8, 4, 6, 8, 9, 9,
        1])
157
2.2630231380462646
tensor([0, 8, 4, 4, 7, 5, 6, 5, 6, 3, 9, 1, 3, 8, 9, 5, 6, 8, 3, 8, 3, 0, 0, 7,
        6])
158
2.296302080154419
tensor([3, 2, 5, 0, 8, 0, 7, 3, 9, 6, 8, 6, 5, 2, 7, 8, 8, 8, 2, 8, 8, 2, 3, 8,
        1])
159
2.2952659130096436
tensor([3, 4, 1, 6, 4, 7, 6, 4, 9, 4, 1, 4, 7, 9, 2, 6, 7, 0, 8, 0, 7, 2, 4, 9,
        3])
160
2.256307363510132
tensor([7, 3, 7, 5, 2, 6, 1, 2, 0, 4, 9, 1, 7, 6, 3, 7, 2, 2, 1, 9, 4, 5, 4, 6,
        2])
161
2.2525224685668945
tensor([8, 6, 9, 7, 3, 1, 1, 4, 7, 9, 5, 4, 7, 6, 8, 3, 9, 5, 7, 5, 0, 8, 5, 7,
        6])
162
2.267162322998047
tensor([1, 3, 1, 9, 2, 4, 7, 9, 2, 0, 9, 1, 7, 6, 9, 5, 8, 5, 2, 2, 7, 7, 9, 5,
        1])
163
2.2639729976654053
tensor([8, 5, 5, 0, 5, 1, 8, 0, 8, 6, 4, 3, 8, 4, 3, 5, 0, 3, 7, 2, 7, 2, 1, 3,
        6])
164
2.2985665798187256
tensor([5, 8, 3, 1, 7, 2, 1, 0, 2, 1, 8, 8, 1, 0, 9, 4, 4, 5, 4, 4, 3, 8, 0, 2,
        2])
165
2.2827370166778564
tensor([4, 3, 3, 0, 8, 4, 1, 0, 1, 7, 9, 5, 6, 5, 1, 4, 5, 3, 8, 7, 3, 7, 3, 7,
        7])
166
2.2858083248138428
tensor([0, 0, 0, 5, 7, 7, 4, 4, 2, 7, 5, 8, 4, 3, 1, 3, 0, 7, 5, 2, 8, 9, 2, 6,
        6])
167
2.263477087020874
tensor([9, 5, 7, 4, 5, 1, 2, 9, 7, 9, 4, 2, 2, 5, 0, 5, 2, 1, 7, 5, 3, 8, 5, 2,
        8])
168
2.268099308013916
tensor([5, 2, 1, 4, 7, 7, 2, 7, 4, 8, 6, 4, 6, 5, 6, 7, 1, 1, 7, 0, 3, 4, 6, 4,
        0])
169
2.244320869445801
tensor([0, 8, 4, 2, 7, 4, 1, 9, 8, 7, 4, 3, 0, 9, 2, 3, 8, 2, 0, 9, 1, 3, 1, 8,
        8])
170
2.2838902473449707
tensor([7, 5, 1, 0, 5, 1, 0, 6, 8, 8, 8, 2, 6, 5, 9, 2, 5, 0, 1, 1, 0, 6, 5, 5,
        8])
171
2.2864458560943604
tensor([5, 4, 3, 7, 7, 8, 1, 9, 2, 5, 7, 8, 2, 5, 8, 5, 3, 4, 9, 8, 6, 7, 3, 1,
        7])
172
2.2645819187164307
tensor([6, 9, 8, 7, 2, 6, 9, 0, 9, 5, 6, 5, 4, 6, 0, 8, 7, 1, 0, 5, 5, 4, 0, 9,
        3])
173
2.273071527481079
tensor([6, 0, 0, 3, 7, 0, 0, 8, 4, 8, 4, 6, 0, 3, 1, 9, 6, 8, 0, 5, 0, 6, 3, 5,
        0])
174
2.298675775527954
tensor([5, 0, 3, 9, 8, 9, 2, 9, 9, 6, 5, 4, 2, 9, 3, 1, 4, 3, 6, 7, 2, 4, 1, 9,
        9])
175
2.274393081665039
tensor([7, 3, 0, 5, 4, 3, 1, 9, 5, 3, 2, 6, 8, 9, 5, 3, 9, 2, 2, 2, 5, 3, 8, 6,