Use the torch.nn module to make the deep learning model easily

In [1]:
import torch
import torch.nn as nn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        # call the constructor function from the nn.Module
        super().__init__()
        
        # the only task of the nn.Lienar is to define a layer of m number of neurons that takes input from n nuerons
        # from previous layers, and perfomrm the linear combination wti the help of the orresponding weight
        self.layer = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.001)
    
    def forward(self, features):
        out = self.layer(features)
        self.y_pred = self.sigmoid(out).to(torch.float64)
        return self.y_pred
    
    def loss_function(self, real_class):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, real_class)
        return self.loss.item()
    
    def optimization(self):
        # it is done so that there won't be previous gradient left which gets added to the new gradient
        self.optimizer.zero_grad()

        # calculate the gradient
        self.loss.backward()

        # backpropagation
        self.optimizer.step()
        return {'weights': self.layer.weight, 'bais' : self.layer.bias}

In [3]:
features = torch.rand(10,5)
print(features)
target = torch.randint(low=0, high= 2, size=(10,1), dtype=torch.float64)
print(target)

tensor([[0.6435, 0.4888, 0.6619, 0.7315, 0.9653],
        [0.2826, 0.5511, 0.1713, 0.0511, 0.3914],
        [0.0015, 0.1577, 0.9824, 0.1138, 0.3485],
        [0.7667, 0.0981, 0.1120, 0.7761, 0.3831],
        [0.1758, 0.8481, 0.7110, 0.2103, 0.1061],
        [0.0187, 0.8107, 0.9319, 0.1183, 0.3226],
        [0.4526, 0.0666, 0.7850, 0.1167, 0.5015],
        [0.8928, 0.3179, 0.4972, 0.6686, 0.5783],
        [0.3473, 0.1165, 0.3010, 0.1662, 0.7277],
        [0.2113, 0.7289, 0.7309, 0.4515, 0.9342]])
tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)

In [4]:
ann = Model(features.shape[1])

In [5]:
y_pred = ann(features)
y_pred

tensor([[0.5061],
        [0.4673],
        [0.3867],
        [0.5300],
        [0.3978],
        [0.3820],
        [0.4388],
        [0.5091],
        [0.4914],
        [0.4612]], dtype=torch.float64, grad_fn=<ToCopyBackward0>)

In [6]:
ann.layer.weight

Parameter containing:
tensor([[ 0.2209, -0.0546, -0.3536,  0.1388,  0.2637]], requires_grad=True)

In [7]:
ann.layer.bias

Parameter containing:
tensor([-0.2131], requires_grad=True)

In [8]:
loss = 1
for epoch in range(20):
    ann(features)
    loss = ann.loss_function(target)
    print("epoch: ", epoch, "===============>  loss:", loss)
    ann.optimization()

print('weight: ', ann.layer.weight)
print('bias: ', ann.layer.bias)

epoch:  0 ===============>  loss: 0.6989098033888264
epoch:  1 ===============>  loss: 0.6988226366474078
epoch:  2 ===============>  loss: 0.6987355357657419
epoch:  3 ===============>  loss: 0.698648498652581
epoch:  4 ===============>  loss: 0.69856154655232
epoch:  5 ===============>  loss: 0.6984746880975349
epoch:  6 ===============>  loss: 0.6983878860964892
epoch:  7 ===============>  loss: 0.6983011901887851
epoch:  8 ===============>  loss: 0.6982145352319363
epoch:  9 ===============>  loss: 0.69812797895283
epoch:  10 ===============>  loss: 0.6980415358360833
epoch:  11 ===============>  loss: 0.6979551302069232
epoch:  12 ===============>  loss: 0.6978688109981872
epoch:  13 ===============>  loss: 0.6977825866129752
epoch:  14 ===============>  loss: 0.6976964370822404
epoch:  15 ===============>  loss: 0.6976103341391352
epoch:  16 ===============>  loss: 0.6975243562584433
epoch:  17 ===============>  loss: 0.6974384471927708
epoch:  18 ===============>  loss: 0.6973525959410989
epoch:  19 ===============>  loss: 0.6972668377214991
weight:  Parameter containing:
tensor([[ 0.2187, -0.0567, -0.3549,  0.1361,  0.2612]], requires_grad=True)
bias:  Parameter containing:
tensor([-0.2162], requires_grad=True)

In [9]:
# ann.layer.parameters() ---> they are the generator so use iteration
for i in ann.layer.parameters():
    print(i)
print("================================================")
for i in ann.layer.named_parameters():
    print(i)

Parameter containing:
tensor([[ 0.2187, -0.0567, -0.3549,  0.1361,  0.2612]], requires_grad=True)
Parameter containing:
tensor([-0.2162], requires_grad=True)
================================================
('weight', Parameter containing:
tensor([[ 0.2187, -0.0567, -0.3549,  0.1361,  0.2612]], requires_grad=True))
('bias', Parameter containing:
tensor([-0.2162], requires_grad=True))

In [124]:
# importing the data as the dataframe from csv file
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [125]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [126]:
# rempving the unwanted features like id and unnamed: 32
df.drop(columns=['id', "Unnamed: 32"], inplace = True)

In [127]:
df.shape

(569, 31)

In [128]:
features = df.iloc[:,1:]
target = df.iloc[:,0]

In [129]:
# split the data set into train and test
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=43)

In [130]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
415,11.89,21.17,76.39,433.8,0.09773,0.08120,0.025550,0.021790,0.2019,0.06290,...,13.05,27.21,85.09,522.9,0.1426,0.21870,0.116400,0.08263,0.3075,0.07351
256,19.55,28.77,133.60,1207.0,0.09260,0.20630,0.178400,0.114400,0.1893,0.06232,...,25.05,36.27,178.60,1926.0,0.1281,0.53290,0.425100,0.19410,0.2818,0.10050
420,11.57,19.04,74.20,409.7,0.08546,0.07722,0.054850,0.014280,0.2031,0.06267,...,13.07,26.98,86.43,520.5,0.1249,0.19370,0.256000,0.06664,0.3035,0.08284
448,14.53,19.34,94.25,659.7,0.08388,0.07800,0.088170,0.029250,0.1473,0.05746,...,16.30,28.39,108.10,830.5,0.1089,0.26490,0.377900,0.09594,0.2471,0.07463
195,12.91,16.33,82.53,516.4,0.07941,0.05366,0.038730,0.023770,0.1829,0.05667,...,13.88,22.00,90.81,600.6,0.1097,0.15060,0.176400,0.08235,0.3024,0.06949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,14.68,20.13,94.74,684.5,0.09867,0.07200,0.073950,0.052590,0.1586,0.05922,...,19.07,30.88,123.40,1138.0,0.1464,0.18710,0.291400,0.16090,0.3029,0.08216
58,13.05,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,0.05501,...,14.23,22.25,90.24,624.1,0.1021,0.06191,0.001845,0.01111,0.2439,0.06289
277,18.81,19.98,120.90,1102.0,0.08923,0.05884,0.080200,0.058430,0.1550,0.04996,...,19.96,24.30,129.00,1236.0,0.1243,0.11600,0.221000,0.12940,0.2567,0.05737
255,13.96,17.05,91.43,602.4,0.10960,0.12790,0.097890,0.052460,0.1908,0.06130,...,16.39,22.07,108.10,826.0,0.1512,0.32620,0.320900,0.13740,0.3068,0.07957
320,10.25,16.18,66.52,324.2,0.10610,0.11110,0.067260,0.039650,0.1743,0.07279,...,11.28,20.61,71.53,390.4,0.1402,0.23600,0.189800,0.09744,0.2608,0.09702

In [131]:
# StandardScaling
scaler = StandardScaler()
# fit_transform will first learn the mean and the s.d. of the trainning data and then do the calculation
# trasnform will that the mean and s.d.of the training data and work for the testing data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [132]:
x_train_scaled[0]

array([-0.63904656,  0.43769321, -0.64504029, -0.62945156,  0.09920259,
       -0.44019265, -0.79716811, -0.6983249 ,  0.72114937,  0.01190875,
       -0.46133074,  0.00649877, -0.45347087, -0.44690619,  0.96005806,
        0.29047614, -0.61987796, -0.40248677,  0.27735408, -0.64126786,
       -0.67242081,  0.24448954, -0.66651354, -0.63112959,  0.44623997,
       -0.24509593, -0.76226753, -0.49515846,  0.26325243, -0.58507738])

In [133]:
# LabelEncoder
y_train
encoder = LabelEncoder()
y_train_labeled = encoder.fit_transform(y_train)
y_test_labeled = encoder.transform(y_test)

In [134]:
# as we work on pyTorch, tensor is required for computation
features_train = torch.from_numpy(x_train_scaled).to(torch.float32)
features_test = torch.from_numpy(x_test_scaled).to(torch.float32)
target_train = torch.from_numpy(y_train_labeled).to(torch.float32)
target_test = torch.from_numpy(y_test_labeled).to(torch.float32)

In [135]:
features_train.shape

torch.Size([455, 30])

In [136]:
target_train.shape

torch.Size([455])

In [169]:

# making a multi-layer ANN with the overfitting control method dropout and fast convergene method BatchNormalization

class ANN_Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # ANN model:
        self.model = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        # optimizer function: 
        self.optim = torch.optim.SGD(self.model.parameters(), lr = 0.1)

    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
        
    def optimizer(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()

In [170]:
model = ANN_Model(features_train.shape[1])

In [171]:
for i in model.model.named_parameters():
    print(i)

('0.weight', Parameter containing:
tensor([[-0.1635, -0.0379,  0.1706, -0.1755,  0.0331, -0.1200, -0.1301,  0.0679,
         -0.0502,  0.0265,  0.0721, -0.0872, -0.0558,  0.0961, -0.0756, -0.1682,
          0.0611,  0.0744, -0.1682, -0.1577,  0.0236,  0.1595, -0.1480,  0.1671,
         -0.1708, -0.1534,  0.0909, -0.0866,  0.0985,  0.1497],
        [-0.0403, -0.0892,  0.1200,  0.0613, -0.0539, -0.0502, -0.1137,  0.0060,
          0.0039,  0.0894, -0.1636, -0.0185, -0.0788, -0.1059, -0.0369,  0.1196,
          0.1068,  0.1582,  0.1729, -0.0449, -0.0364, -0.0480,  0.0821,  0.0003,
         -0.1289, -0.1043, -0.1618, -0.0915, -0.1138,  0.1339],
        [-0.0166,  0.1633,  0.1655,  0.1223, -0.0010,  0.1456, -0.1129, -0.1035,
         -0.1797, -0.1331, -0.1598,  0.0409,  0.0924, -0.0308,  0.0371,  0.1604,
          0.0940,  0.0787, -0.0619,  0.1004,  0.0234,  0.0394,  0.0955, -0.0854,
          0.0898, -0.1536, -0.0189, -0.0644,  0.1110, -0.1370]],
       requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.1118, -0.1416,  0.1055], requires_grad=True))
('2.weight', Parameter containing:
tensor([[-0.3873,  0.4485, -0.2947]], requires_grad=True))
('2.bias', Parameter containing:
tensor([0.4025], requires_grad=True))

In [172]:
epoch = 20

In [173]:
target_train_dim = target_train.reshape(features_train.shape[0],1).clone()

In [174]:
y_pred

tensor([8.0367e-06], grad_fn=<SigmoidBackward0>)

## Stochastic Gradient Descent

In [175]:
# Stochastic Gradient Descent
for i in range(1):
    print("epoch:", i)
    for data_record in range(features_train.shape[0]):
        y_pred = model(features_train[data_record])
        print("data_record", data_record, "predicted_value", y_pred)
        loss = model.loss_function(target_train_dim[data_record])
        print("loss", loss)
        model.optimizer()

epoch: 0
data_record 0 predicted_value tensor([0.5890], grad_fn=<SigmoidBackward0>)
loss 0.8891296982765198
data_record 1 predicted_value tensor([0.5450], grad_fn=<SigmoidBackward0>)
loss 0.6069965958595276
data_record 2 predicted_value tensor([0.5631], grad_fn=<SigmoidBackward0>)
loss 0.8281326293945312
data_record 3 predicted_value tensor([0.5167], grad_fn=<SigmoidBackward0>)
loss 0.7270515561103821
data_record 4 predicted_value tensor([0.4746], grad_fn=<SigmoidBackward0>)
loss 0.6435790657997131
data_record 5 predicted_value tensor([0.5581], grad_fn=<SigmoidBackward0>)
loss 0.5831400156021118
data_record 6 predicted_value tensor([0.5690], grad_fn=<SigmoidBackward0>)
loss 0.5638566017150879
data_record 7 predicted_value tensor([0.5390], grad_fn=<SigmoidBackward0>)
loss 0.7742968201637268
data_record 8 predicted_value tensor([0.5286], grad_fn=<SigmoidBackward0>)
loss 0.7520526647567749
data_record 9 predicted_value tensor([0.5533], grad_fn=<SigmoidBackward0>)
loss 0.591791033744812
data_record 10 predicted_value tensor([0.6573], grad_fn=<SigmoidBackward0>)
loss 0.419622004032135
data_record 11 predicted_value tensor([0.3223], grad_fn=<SigmoidBackward0>)
loss 0.38901692628860474
data_record 12 predicted_value tensor([0.4575], grad_fn=<SigmoidBackward0>)
loss 0.6114899516105652
data_record 13 predicted_value tensor([0.3478], grad_fn=<SigmoidBackward0>)
loss 0.4274604618549347
data_record 14 predicted_value tensor([0.3145], grad_fn=<SigmoidBackward0>)
loss 0.37761586904525757
data_record 15 predicted_value tensor([0.6125], grad_fn=<SigmoidBackward0>)
loss 0.49016398191452026
data_record 16 predicted_value tensor([0.2479], grad_fn=<SigmoidBackward0>)
loss 0.2848232388496399
data_record 17 predicted_value tensor([0.1940], grad_fn=<SigmoidBackward0>)
loss 0.21569879353046417
data_record 18 predicted_value tensor([0.0835], grad_fn=<SigmoidBackward0>)
loss 0.08721789717674255
data_record 19 predicted_value tensor([0.1242], grad_fn=<SigmoidBackward0>)
loss 0.13264985382556915
data_record 20 predicted_value tensor([0.1875], grad_fn=<SigmoidBackward0>)
loss 0.20768913626670837
data_record 21 predicted_value tensor([0.1175], grad_fn=<SigmoidBackward0>)
loss 0.12494123727083206
data_record 22 predicted_value tensor([0.0681], grad_fn=<SigmoidBackward0>)
loss 0.0704883486032486
data_record 23 predicted_value tensor([0.6386], grad_fn=<SigmoidBackward0>)
loss 1.017684817314148
data_record 24 predicted_value tensor([0.1819], grad_fn=<SigmoidBackward0>)
loss 0.20071952044963837
data_record 25 predicted_value tensor([0.0268], grad_fn=<SigmoidBackward0>)
loss 0.02714420296251774
data_record 26 predicted_value tensor([0.5135], grad_fn=<SigmoidBackward0>)
loss 0.7204204201698303
data_record 27 predicted_value tensor([0.0266], grad_fn=<SigmoidBackward0>)
loss 0.026975898072123528
data_record 28 predicted_value tensor([0.5568], grad_fn=<SigmoidBackward0>)
loss 0.5855408906936646
data_record 29 predicted_value tensor([0.1605], grad_fn=<SigmoidBackward0>)
loss 0.1750071942806244
data_record 30 predicted_value tensor([0.0398], grad_fn=<SigmoidBackward0>)
loss 0.04063250869512558
data_record 31 predicted_value tensor([0.1580], grad_fn=<SigmoidBackward0>)
loss 0.17192773520946503
data_record 32 predicted_value tensor([0.1308], grad_fn=<SigmoidBackward0>)
loss 2.0339272022247314
data_record 33 predicted_value tensor([0.3694], grad_fn=<SigmoidBackward0>)
loss 0.46112024784088135
data_record 34 predicted_value tensor([0.1332], grad_fn=<SigmoidBackward0>)
loss 0.14295534789562225
data_record 35 predicted_value tensor([0.0591], grad_fn=<SigmoidBackward0>)
loss 0.060938168317079544
data_record 36 predicted_value tensor([0.5700], grad_fn=<SigmoidBackward0>)
loss 0.562053382396698
data_record 37 predicted_value tensor([0.0728], grad_fn=<SigmoidBackward0>)
loss 0.07554791122674942
data_record 38 predicted_value tensor([0.2583], grad_fn=<SigmoidBackward0>)
loss 0.29880571365356445
data_record 39 predicted_value tensor([0.6786], grad_fn=<SigmoidBackward0>)
loss 0.3876725435256958
data_record 40 predicted_value tensor([0.5745], grad_fn=<SigmoidBackward0>)
loss 0.5542241930961609
data_record 41 predicted_value tensor([0.1354], grad_fn=<SigmoidBackward0>)
loss 0.14549678564071655
data_record 42 predicted_value tensor([0.1596], grad_fn=<SigmoidBackward0>)
loss 0.173880934715271
data_record 43 predicted_value tensor([0.6828], grad_fn=<SigmoidBackward0>)
loss 0.3816189467906952
data_record 44 predicted_value tensor([0.0952], grad_fn=<SigmoidBackward0>)
loss 0.10002054274082184
data_record 45 predicted_value tensor([0.5639], grad_fn=<SigmoidBackward0>)
loss 0.5727934837341309
data_record 46 predicted_value tensor([0.9203], grad_fn=<SigmoidBackward0>)
loss 0.08306845277547836
data_record 47 predicted_value tensor([0.4655], grad_fn=<SigmoidBackward0>)
loss 0.7646778225898743
data_record 48 predicted_value tensor([0.0655], grad_fn=<SigmoidBackward0>)
loss 0.06779073178768158
data_record 49 predicted_value tensor([0.9453], grad_fn=<SigmoidBackward0>)
loss 0.05621973052620888
data_record 50 predicted_value tensor([0.0039], grad_fn=<SigmoidBackward0>)
loss 0.003949487581849098
data_record 51 predicted_value tensor([0.0152], grad_fn=<SigmoidBackward0>)
loss 0.015355457551777363
data_record 52 predicted_value tensor([0.0049], grad_fn=<SigmoidBackward0>)
loss 0.004931383300572634
data_record 53 predicted_value tensor([0.0465], grad_fn=<SigmoidBackward0>)
loss 0.04764779657125473
data_record 54 predicted_value tensor([0.0091], grad_fn=<SigmoidBackward0>)
loss 0.00918780080974102
data_record 55 predicted_value tensor([0.8414], grad_fn=<SigmoidBackward0>)
loss 0.1726636290550232
data_record 56 predicted_value tensor([0.6642], grad_fn=<SigmoidBackward0>)
loss 0.409180223941803
data_record 57 predicted_value tensor([0.0607], grad_fn=<SigmoidBackward0>)
loss 0.0625673457980156
data_record 58 predicted_value tensor([0.0107], grad_fn=<SigmoidBackward0>)
loss 0.010729738511145115
data_record 59 predicted_value tensor([0.0183], grad_fn=<SigmoidBackward0>)
loss 0.018463395535945892
data_record 60 predicted_value tensor([0.6120], grad_fn=<SigmoidBackward0>)
loss 0.4909542500972748
data_record 61 predicted_value tensor([0.0231], grad_fn=<SigmoidBackward0>)
loss 0.02333076111972332
data_record 62 predicted_value tensor([0.0052], grad_fn=<SigmoidBackward0>)
loss 0.005186768248677254
data_record 63 predicted_value tensor([0.0081], grad_fn=<SigmoidBackward0>)
loss 0.008138105273246765
data_record 64 predicted_value tensor([0.9682], grad_fn=<SigmoidBackward0>)
loss 0.03235775977373123
data_record 65 predicted_value tensor([0.0282], grad_fn=<SigmoidBackward0>)
loss 0.02862849459052086
data_record 66 predicted_value tensor([0.9947], grad_fn=<SigmoidBackward0>)
loss 0.005300418008118868
data_record 67 predicted_value tensor([0.0360], grad_fn=<SigmoidBackward0>)
loss 0.03663301095366478
data_record 68 predicted_value tensor([0.0315], grad_fn=<SigmoidBackward0>)
loss 0.032057031989097595
data_record 69 predicted_value tensor([0.8788], grad_fn=<SigmoidBackward0>)
loss 0.1292460560798645
data_record 70 predicted_value tensor([0.0648], grad_fn=<SigmoidBackward0>)
loss 0.06702408939599991
data_record 71 predicted_value tensor([0.0505], grad_fn=<SigmoidBackward0>)
loss 0.051849208772182465
data_record 72 predicted_value tensor([0.4494], grad_fn=<SigmoidBackward0>)
loss 0.5968024730682373
data_record 73 predicted_value tensor([0.0059], grad_fn=<SigmoidBackward0>)
loss 0.005945947952568531
data_record 74 predicted_value tensor([0.7218], grad_fn=<SigmoidBackward0>)
loss 0.3259413242340088
data_record 75 predicted_value tensor([0.0042], grad_fn=<SigmoidBackward0>)
loss 0.004158917814493179
data_record 76 predicted_value tensor([0.0062], grad_fn=<SigmoidBackward0>)
loss 0.006215832196176052
data_record 77 predicted_value tensor([0.0002], grad_fn=<SigmoidBackward0>)
loss 0.0001928818819578737
data_record 78 predicted_value tensor([0.0448], grad_fn=<SigmoidBackward0>)
loss 0.04584851861000061
data_record 79 predicted_value tensor([0.5514], grad_fn=<SigmoidBackward0>)
loss 0.8015638589859009
data_record 80 predicted_value tensor([0.1910], grad_fn=<SigmoidBackward0>)
loss 0.21200792491436005
data_record 81 predicted_value tensor([0.0001], grad_fn=<SigmoidBackward0>)
loss 0.00010789332736749202
data_record 82 predicted_value tensor([0.9907], grad_fn=<SigmoidBackward0>)
loss 0.009366010315716267
data_record 83 predicted_value tensor([0.9458], grad_fn=<SigmoidBackward0>)
loss 0.05568443983793259
data_record 84 predicted_value tensor([0.9678], grad_fn=<SigmoidBackward0>)
loss 0.03275320678949356
data_record 85 predicted_value tensor([0.9088], grad_fn=<SigmoidBackward0>)
loss 0.09564563632011414
data_record 86 predicted_value tensor([0.0396], grad_fn=<SigmoidBackward0>)
loss 0.04039633274078369
data_record 87 predicted_value tensor([0.2559], grad_fn=<SigmoidBackward0>)
loss 0.29564425349235535
data_record 88 predicted_value tensor([0.0029], grad_fn=<SigmoidBackward0>)
loss 0.0029015070758759975
data_record 89 predicted_value tensor([0.0484], grad_fn=<SigmoidBackward0>)
loss 0.04960887134075165
data_record 90 predicted_value tensor([0.0047], grad_fn=<SigmoidBackward0>)
loss 0.004672849550843239
data_record 91 predicted_value tensor([0.9820], grad_fn=<SigmoidBackward0>)
loss 0.018140245229005814
data_record 92 predicted_value tensor([0.0019], grad_fn=<SigmoidBackward0>)
loss 0.0018834011862054467
data_record 93 predicted_value tensor([0.0043], grad_fn=<SigmoidBackward0>)
loss 0.00427002040669322
data_record 94 predicted_value tensor([0.9995], grad_fn=<SigmoidBackward0>)
loss 0.0004841068875975907
data_record 95 predicted_value tensor([0.2668], grad_fn=<SigmoidBackward0>)
loss 1.3212274312973022
data_record 96 predicted_value tensor([0.0348], grad_fn=<SigmoidBackward0>)
loss 0.03545154258608818
data_record 97 predicted_value tensor([0.0014], grad_fn=<SigmoidBackward0>)
loss 0.0014241692842915654
data_record 98 predicted_value tensor([0.0100], grad_fn=<SigmoidBackward0>)
loss 0.010066717863082886
data_record 99 predicted_value tensor([0.0035], grad_fn=<SigmoidBackward0>)
loss 0.003538434626534581
data_record 100 predicted_value tensor([0.2457], grad_fn=<SigmoidBackward0>)
loss 0.28190258145332336
data_record 101 predicted_value tensor([0.9838], grad_fn=<SigmoidBackward0>)
loss 0.016299884766340256
data_record 102 predicted_value tensor([0.9703], grad_fn=<SigmoidBackward0>)
loss 0.03017975203692913
data_record 103 predicted_value tensor([0.6674], grad_fn=<SigmoidBackward0>)
loss 0.4044351875782013
data_record 104 predicted_value tensor([0.0286], grad_fn=<SigmoidBackward0>)
loss 0.029029931873083115
data_record 105 predicted_value tensor([0.4038], grad_fn=<SigmoidBackward0>)
loss 0.9069198966026306
data_record 106 predicted_value tensor([0.9576], grad_fn=<SigmoidBackward0>)
loss 0.043299730867147446
data_record 107 predicted_value tensor([0.5632], grad_fn=<SigmoidBackward0>)
loss 0.8282393217086792
data_record 108 predicted_value tensor([0.0009], grad_fn=<SigmoidBackward0>)
loss 0.0008763092337176204
data_record 109 predicted_value tensor([0.9999], grad_fn=<SigmoidBackward0>)
loss 0.00010741333971964195
data_record 110 predicted_value tensor([0.0011], grad_fn=<SigmoidBackward0>)
loss 0.0011204392649233341
data_record 111 predicted_value tensor([0.0006], grad_fn=<SigmoidBackward0>)
loss 0.0006206266698427498
data_record 112 predicted_value tensor([0.2579], grad_fn=<SigmoidBackward0>)
loss 0.29830074310302734
data_record 113 predicted_value tensor([0.0029], grad_fn=<SigmoidBackward0>)
loss 0.0029052449390292168
data_record 114 predicted_value tensor([0.0017], grad_fn=<SigmoidBackward0>)
loss 0.0017498924862593412
data_record 115 predicted_value tensor([0.2216], grad_fn=<SigmoidBackward0>)
loss 1.506845235824585
data_record 116 predicted_value tensor([0.9504], grad_fn=<SigmoidBackward0>)
loss 0.050912726670503616
data_record 117 predicted_value tensor([0.3995], grad_fn=<SigmoidBackward0>)
loss 0.9175996780395508
data_record 118 predicted_value tensor([0.9856], grad_fn=<SigmoidBackward0>)
loss 0.014538074843585491
data_record 119 predicted_value tensor([0.9966], grad_fn=<SigmoidBackward0>)
loss 0.003357497276738286
data_record 120 predicted_value tensor([0.9633], grad_fn=<SigmoidBackward0>)
loss 0.03737561032176018
data_record 121 predicted_value tensor([0.0005], grad_fn=<SigmoidBackward0>)
loss 0.0005314730806276202
data_record 122 predicted_value tensor([0.0093], grad_fn=<SigmoidBackward0>)
loss 0.00933924037963152
data_record 123 predicted_value tensor([0.0076], grad_fn=<SigmoidBackward0>)
loss 0.0076417564414441586
data_record 124 predicted_value tensor([0.0058], grad_fn=<SigmoidBackward0>)
loss 0.0058471024967730045
data_record 125 predicted_value tensor([0.9495], grad_fn=<SigmoidBackward0>)
loss 0.05184740573167801
data_record 126 predicted_value tensor([0.9979], grad_fn=<SigmoidBackward0>)
loss 0.0020555509254336357
data_record 127 predicted_value tensor([0.9998], grad_fn=<SigmoidBackward0>)
loss 0.00022002494370099157
data_record 128 predicted_value tensor([0.9950], grad_fn=<SigmoidBackward0>)
loss 0.005048959515988827
data_record 129 predicted_value tensor([0.8245], grad_fn=<SigmoidBackward0>)
loss 0.19297203421592712
data_record 130 predicted_value tensor([0.1352], grad_fn=<SigmoidBackward0>)
loss 0.14520342648029327
data_record 131 predicted_value tensor([0.5907], grad_fn=<SigmoidBackward0>)
loss 0.5263904333114624
data_record 132 predicted_value tensor([0.9712], grad_fn=<SigmoidBackward0>)
loss 0.029219739139080048
data_record 133 predicted_value tensor([0.0155], grad_fn=<SigmoidBackward0>)
loss 0.015589559450745583
data_record 134 predicted_value tensor([0.0003], grad_fn=<SigmoidBackward0>)
loss 0.0003108489909209311
data_record 135 predicted_value tensor([0.0043], grad_fn=<SigmoidBackward0>)
loss 0.0043485029600560665
data_record 136 predicted_value tensor([0.0209], grad_fn=<SigmoidBackward0>)
loss 0.021143190562725067
data_record 137 predicted_value tensor([0.2106], grad_fn=<SigmoidBackward0>)
loss 0.23651063442230225
data_record 138 predicted_value tensor([0.0006], grad_fn=<SigmoidBackward0>)
loss 0.0006498619914054871
data_record 139 predicted_value tensor([0.9989], grad_fn=<SigmoidBackward0>)
loss 0.0011216133134439588
data_record 140 predicted_value tensor([0.9230], grad_fn=<SigmoidBackward0>)
loss 0.08013485372066498
data_record 141 predicted_value tensor([0.0386], grad_fn=<SigmoidBackward0>)
loss 0.039403196424245834
data_record 142 predicted_value tensor([0.4330], grad_fn=<SigmoidBackward0>)
loss 0.5673584938049316
data_record 143 predicted_value tensor([0.0007], grad_fn=<SigmoidBackward0>)
loss 0.0006512065301649272
data_record 144 predicted_value tensor([0.0753], grad_fn=<SigmoidBackward0>)
loss 0.07832429558038712
data_record 145 predicted_value tensor([0.9738], grad_fn=<SigmoidBackward0>)
loss 0.026598483324050903
data_record 146 predicted_value tensor([0.9596], grad_fn=<SigmoidBackward0>)
loss 0.041212379932403564
data_record 147 predicted_value tensor([0.9966], grad_fn=<SigmoidBackward0>)
loss 0.0033998999278992414
data_record 148 predicted_value tensor([0.9928], grad_fn=<SigmoidBackward0>)
loss 0.007273357827216387
data_record 149 predicted_value tensor([0.9243], grad_fn=<SigmoidBackward0>)
loss 0.07869496941566467
data_record 150 predicted_value tensor([0.0011], grad_fn=<SigmoidBackward0>)
loss 0.0011200340231880546
data_record 151 predicted_value tensor([0.0018], grad_fn=<SigmoidBackward0>)
loss 0.0017751072300598025
data_record 152 predicted_value tensor([0.0184], grad_fn=<SigmoidBackward0>)
loss 0.01861330308020115
data_record 153 predicted_value tensor([0.9631], grad_fn=<SigmoidBackward0>)
loss 0.037602223455905914
data_record 154 predicted_value tensor([0.0065], grad_fn=<SigmoidBackward0>)
loss 0.006519032176584005
data_record 155 predicted_value tensor([1.0000], grad_fn=<SigmoidBackward0>)
loss 1.0728841743912199e-06
data_record 156 predicted_value tensor([0.1552], grad_fn=<SigmoidBackward0>)
loss 0.1686810851097107
data_record 157 predicted_value tensor([0.0260], grad_fn=<SigmoidBackward0>)
loss 0.02637750655412674
data_record 158 predicted_value tensor([0.5286], grad_fn=<SigmoidBackward0>)
loss 0.6374719142913818
data_record 159 predicted_value tensor([0.9706], grad_fn=<SigmoidBackward0>)
loss 0.029829103499650955
data_record 160 predicted_value tensor([0.9929], grad_fn=<SigmoidBackward0>)
loss 0.007133354898542166
data_record 161 predicted_value tensor([0.9999], grad_fn=<SigmoidBackward0>)
loss 5.757974577136338e-05
data_record 162 predicted_value tensor([0.4389], grad_fn=<SigmoidBackward0>)
loss 0.5777928233146667
data_record 163 predicted_value tensor([0.0013], grad_fn=<SigmoidBackward0>)
loss 0.0013019551988691092
data_record 164 predicted_value tensor([0.0046], grad_fn=<SigmoidBackward0>)
loss 0.004608609713613987
data_record 165 predicted_value tensor([0.9932], grad_fn=<SigmoidBackward0>)
loss 0.006779293064028025
data_record 166 predicted_value tensor([0.9965], grad_fn=<SigmoidBackward0>)
loss 0.0034569581039249897
data_record 167 predicted_value tensor([0.0305], grad_fn=<SigmoidBackward0>)
loss 0.03099636174738407
data_record 168 predicted_value tensor([0.9980], grad_fn=<SigmoidBackward0>)
loss 0.0020066353026777506
data_record 169 predicted_value tensor([0.9945], grad_fn=<SigmoidBackward0>)
loss 0.0054882294498384
data_record 170 predicted_value tensor([0.0324], grad_fn=<SigmoidBackward0>)
loss 0.03295965865254402
data_record 171 predicted_value tensor([0.0003], grad_fn=<SigmoidBackward0>)
loss 0.0002623524924274534
data_record 172 predicted_value tensor([0.0002], grad_fn=<SigmoidBackward0>)
loss 0.00023218283604364842
data_record 173 predicted_value tensor([0.9913], grad_fn=<SigmoidBackward0>)
loss 0.008733990602195263
data_record 174 predicted_value tensor([0.3071], grad_fn=<SigmoidBackward0>)
loss 1.180461049079895
data_record 175 predicted_value tensor([0.0020], grad_fn=<SigmoidBackward0>)
loss 0.001991312252357602
data_record 176 predicted_value tensor([0.9239], grad_fn=<SigmoidBackward0>)
loss 0.07914794236421585
data_record 177 predicted_value tensor([0.9986], grad_fn=<SigmoidBackward0>)
loss 0.0014285511570051312
data_record 178 predicted_value tensor([4.1190e-05], grad_fn=<SigmoidBackward0>)
loss 4.119073128094897e-05
data_record 179 predicted_value tensor([0.0050], grad_fn=<SigmoidBackward0>)
loss 0.0050033205188810825
data_record 180 predicted_value tensor([0.0067], grad_fn=<SigmoidBackward0>)
loss 0.006721296813338995
data_record 181 predicted_value tensor([0.0069], grad_fn=<SigmoidBackward0>)
loss 0.006918916944414377
data_record 182 predicted_value tensor([0.0339], grad_fn=<SigmoidBackward0>)
loss 0.0345151387155056
data_record 183 predicted_value tensor([0.1590], grad_fn=<SigmoidBackward0>)
loss 0.17318600416183472
data_record 184 predicted_value tensor([3.5734e-05], grad_fn=<SigmoidBackward0>)
loss 3.57346361852251e-05
data_record 185 predicted_value tensor([9.4764e-05], grad_fn=<SigmoidBackward0>)
loss 9.476844570599496e-05
data_record 186 predicted_value tensor([0.1975], grad_fn=<SigmoidBackward0>)
loss 0.2200307846069336
data_record 187 predicted_value tensor([0.0012], grad_fn=<SigmoidBackward0>)
loss 0.0011565258027985692
data_record 188 predicted_value tensor([0.9805], grad_fn=<SigmoidBackward0>)
loss 0.019734596833586693
data_record 189 predicted_value tensor([0.9987], grad_fn=<SigmoidBackward0>)
loss 0.0012741454411298037
data_record 190 predicted_value tensor([0.0236], grad_fn=<SigmoidBackward0>)
loss 0.023868756368756294
data_record 191 predicted_value tensor([0.0125], grad_fn=<SigmoidBackward0>)
loss 0.01255069300532341
data_record 192 predicted_value tensor([0.0075], grad_fn=<SigmoidBackward0>)
loss 0.00748456222936511
data_record 193 predicted_value tensor([0.0029], grad_fn=<SigmoidBackward0>)
loss 0.002906509442254901
data_record 194 predicted_value tensor([5.6132e-05], grad_fn=<SigmoidBackward0>)
loss 5.61337401450146e-05
data_record 195 predicted_value tensor([0.0013], grad_fn=<SigmoidBackward0>)
loss 0.0013278876431286335

## Batch Gradient Descent

In [192]:
# Batch Gradient Descent
for i in range(epoch):
    y_pred  = model.forward(features_train)
    loss = model.loss_function(target_train_dim)
    model.optimizer()
    print("epoch:",i, "loss:", loss)

epoch: 0 loss: 0.0825735405087471
epoch: 1 loss: 0.08136510848999023
epoch: 2 loss: 0.08014874905347824
epoch: 3 loss: 0.07891526073217392
epoch: 4 loss: 0.07775707542896271
epoch: 5 loss: 0.07666845619678497
epoch: 6 loss: 0.0756441280245781
epoch: 7 loss: 0.07467931509017944
epoch: 8 loss: 0.0737699419260025
epoch: 9 loss: 0.0729183778166771
epoch: 10 loss: 0.07212629169225693
epoch: 11 loss: 0.07137759029865265
epoch: 12 loss: 0.07066915184259415
epoch: 13 loss: 0.0699981302022934
epoch: 14 loss: 0.06936191022396088
epoch: 15 loss: 0.0687527060508728
epoch: 16 loss: 0.06814304739236832
epoch: 17 loss: 0.06756400316953659
epoch: 18 loss: 0.06701350957155228
epoch: 19 loss: 0.06648965179920197

In [193]:
y_pred

tensor([[2.4398e-02],
        [9.9999e-01],
        [1.1321e-02],
        [3.0611e-01],
        [7.2964e-03],
        [9.8794e-01],
        [9.9970e-01],
        [3.0595e-03],
        [4.6540e-02],
        [9.9999e-01],
        [9.9994e-01],
        [1.0584e-03],
        [5.6681e-04],
        [2.3422e-01],
        [4.0042e-04],
        [9.9896e-01],
        [1.1036e-02],
        [6.4903e-02],
        [5.6647e-02],
        [4.5667e-03],
        [6.4396e-04],
        [8.3752e-03],
        [2.4477e-02],
        [2.1479e-05],
        [5.6659e-03],
        [2.1957e-02],
        [8.2498e-03],
        [1.8964e-03],
        [9.9995e-01],
        [3.7584e-03],
        [6.7038e-03],
        [1.2132e-04],
        [4.1687e-01],
        [9.0492e-01],
        [1.0175e-01],
        [4.5831e-04],
        [9.9959e-01],
        [3.1836e-03],
        [1.6334e-04],
        [1.0000e+00],
        [9.5169e-01],
        [5.6588e-03],
        [1.4965e-02],
        [9.9798e-01],
        [3.5738e-01],
        [9.9999e-01],
        [1.0000e+00],
        [9.6283e-01],
        [6.7655e-03],
        [1.0000e+00],
        [1.1680e-04],
        [2.9782e-04],
        [8.0150e-06],
        [4.2181e-02],
        [1.2124e-05],
        [9.9728e-01],
        [9.9960e-01],
        [4.1456e-03],
        [1.6539e-02],
        [1.3660e-02],
        [9.2908e-01],
        [1.7550e-03],
        [6.7986e-04],
        [7.8157e-03],
        [9.9999e-01],
        [6.5550e-03],
        [1.0000e+00],
        [9.6020e-03],
        [7.5195e-03],
        [9.9959e-01],
        [4.8340e-02],
        [1.0191e-01],
        [6.3346e-01],
        [1.5400e-04],
        [9.9622e-01],
        [6.4991e-04],
        [1.8906e-03],
        [1.3046e-05],
        [1.4147e-05],
        [6.2502e-01],
        [4.5212e-02],
        [5.5521e-06],
        [1.0000e+00],
        [9.9992e-01],
        [9.9999e-01],
        [9.9782e-01],
        [1.8772e-03],
        [2.8924e-02],
        [1.3502e-03],
        [2.9487e-01],
        [8.0229e-03],
        [1.0000e+00],
        [4.5145e-04],
        [3.8170e-04],
        [1.0000e+00],
        [8.6993e-01],
        [1.1816e-02],
        [2.0635e-04],
        [3.5594e-03],
        [8.4340e-04],
        [4.8210e-01],
        [9.9999e-01],
        [9.9905e-01],
        [9.4196e-01],
        [5.5973e-02],
        [7.8493e-01],
        [9.9953e-01],
        [6.1030e-01],
        [6.9701e-05],
        [1.0000e+00],
        [1.5616e-04],
        [4.6408e-05],
        [6.2502e-01],
        [2.9947e-03],
        [4.3683e-03],
        [7.2419e-01],
        [9.9975e-01],
        [9.1382e-01],
        [9.9086e-01],
        [9.9993e-01],
        [9.8797e-01],
        [1.5375e-05],
        [1.1084e-03],
        [7.5139e-04],
        [1.9270e-04],
        [9.9761e-01],
        [1.0000e+00],
        [1.0000e+00],
        [9.9970e-01],
        [9.8508e-01],
        [6.4467e-02],
        [6.8431e-01],
        [9.9703e-01],
        [8.5813e-03],
        [5.8092e-06],
        [5.5004e-04],
        [2.6298e-02],
        [2.7832e-01],
        [1.4223e-03],
        [1.0000e+00],
        [9.7940e-01],
        [4.6900e-02],
        [1.0765e-01],
        [2.0446e-04],
        [4.9129e-02],
        [9.9237e-01],
        [9.9873e-01],
        [9.9880e-01],
        [9.9989e-01],
        [9.5610e-01],
        [1.5749e-04],
        [2.6689e-04],
        [2.5261e-02],
        [9.9941e-01],
        [4.7525e-03],
        [1.0000e+00],
        [7.9760e-02],
        [5.5993e-02],
        [7.1721e-01],
        [9.9171e-01],
        [9.9700e-01],
        [1.0000e+00],
        [1.4664e-01],
        [1.1364e-03],
        [7.8202e-03],
        [9.9985e-01],
        [9.9996e-01],
        [2.0098e-02],
        [1.0000e+00],
        [9.9958e-01],
        [1.1542e-01],
        [8.5076e-05],
        [7.2195e-05],
        [9.9994e-01],
        [9.7852e-01],
        [1.0490e-03],
        [9.8970e-01],
        [9.9999e-01],
        [2.0701e-05],
        [5.0160e-03],
        [4.0196e-03],
        [7.8799e-03],
        [3.8002e-02],
        [2.1390e-01],
        [4.9567e-05],
        [4.1026e-05],
        [1.8481e-01],
        [3.7702e-03],
        [9.9788e-01],
        [9.9998e-01],
        [4.2306e-02],
        [1.9665e-02],
        [8.6197e-03],
        [2.1062e-03],
        [4.4839e-05],
        [3.6212e-04],
        [2.1726e-01],
        [1.0939e-01],
        [5.7993e-03],
        [9.9596e-01],
        [3.3881e-04],
        [1.0000e+00],
        [1.2573e-06],
        [6.1831e-04],
        [5.8223e-05],
        [1.0000e+00],
        [1.3446e-02],
        [9.9219e-01],
        [1.0000e+00],
        [9.9935e-01],
        [1.0000e+00],
        [5.0206e-05],
        [1.3282e-03],
        [9.9998e-01],
        [9.9613e-01],
        [4.5214e-02],
        [2.5038e-03],
        [1.0558e-04],
        [5.8486e-05],
        [9.9990e-01],
        [3.0819e-03],
        [9.9886e-01],
        [1.4736e-01],
        [9.9845e-01],
        [2.2090e-01],
        [2.2953e-02],
        [3.5904e-01],
        [3.1596e-05],
        [1.7411e-05],
        [1.5764e-02],
        [4.0221e-03],
        [8.2000e-01],
        [9.7188e-01],
        [1.9689e-03],
        [1.4820e-03],
        [3.4929e-02],
        [9.9997e-01],
        [3.5115e-04],
        [9.9996e-01],
        [9.4131e-03],
        [8.2381e-01],
        [9.9734e-01],
        [3.6252e-04],
        [2.4347e-03],
        [8.8589e-01],
        [9.9926e-01],
        [5.9091e-02],
        [7.0201e-02],
        [4.7252e-03],
        [5.1195e-04],
        [2.5696e-01],
        [1.0000e+00],
        [9.9991e-01],
        [1.6865e-01],
        [7.2351e-04],
        [2.6209e-06],
        [9.9899e-01],
        [6.7692e-04],
        [9.9984e-01],
        [9.1977e-01],
        [9.8435e-04],
        [2.3137e-04],
        [4.0304e-04],
        [1.4421e-02],
        [6.8132e-02],
        [2.6912e-02],
        [9.8508e-01],
        [1.8368e-05],
        [3.1326e-01],
        [9.9993e-01],
        [9.9984e-01],
        [1.2153e-03],
        [1.5135e-04],
        [1.6495e-02],
        [2.5024e-02],
        [6.4099e-03],
        [9.2693e-01],
        [4.7187e-03],
        [2.4485e-03],
        [2.2475e-01],
        [1.5037e-07],
        [7.5364e-04],
        [9.5765e-04],
        [8.9255e-01],
        [1.5430e-01],
        [1.0761e-01],
        [7.7467e-02],
        [1.2634e-01],
        [2.5123e-04],
        [5.7566e-01],
        [9.9995e-01],
        [4.4687e-04],
        [1.0000e+00],
        [6.2502e-01],
        [4.1127e-04],
        [5.1176e-06],
        [1.4758e-02],
        [9.9999e-01],
        [3.4683e-04],
        [9.9163e-01],
        [1.2995e-01],
        [5.3536e-03],
        [9.9991e-01],
        [1.8803e-02],
        [9.9711e-01],
        [1.1430e-02],
        [9.9992e-01],
        [1.6174e-02],
        [5.1688e-04],
        [1.1784e-02],
        [2.6001e-05],
        [2.2601e-04],
        [1.5685e-04],
        [9.9533e-01],
        [1.5471e-02],
        [9.9907e-01],
        [1.0000e+00],
        [2.9466e-04],
        [9.9962e-01],
        [9.9999e-01],
        [2.9457e-01],
        [9.9999e-01],
        [9.9996e-01],
        [1.4307e-04],
        [1.3928e-02],
        [1.0000e+00],
        [9.9848e-01],
        [1.0993e-04],
        [1.0021e-01],
        [2.8727e-04],
        [8.0229e-03],
        [9.9997e-01],
        [9.9997e-01],
        [9.9999e-01],
        [9.4219e-01],
        [1.2884e-02],
        [8.2783e-04],
        [3.7271e-02],
        [6.6932e-01],
        [1.5206e-03],
        [1.1889e-03],
        [3.4402e-05],
        [1.0000e+00],
        [9.4919e-02],
        [3.6432e-03],
        [8.1371e-02],
        [9.6981e-01],
        [9.9882e-01],
        [3.4871e-03],
        [6.8670e-06],
        [8.6576e-01],
        [1.9227e-06],
        [6.4277e-03],
        [1.0000e+00],
        [2.2776e-01],
        [1.0171e-01],
        [1.7575e-01],
        [1.2579e-02],
        [2.4530e-03],
        [2.6779e-02],
        [1.4470e-03],
        [6.5620e-02],
        [9.8082e-01],
        [9.6302e-01],
        [1.0000e+00],
        [3.1596e-04],
        [9.9932e-01],
        [1.0000e+00],
        [4.4080e-04],
        [1.0000e+00],
        [2.6067e-03],
        [9.9991e-01],
        [7.0342e-01],
        [1.0000e+00],
        [6.6893e-03],
        [1.1829e-03],
        [8.4182e-05],
        [9.9969e-01],
        [4.2628e-01],
        [5.3353e-02],
        [9.4309e-02],
        [7.2288e-06],
        [9.9818e-01],
        [2.3146e-04],
        [9.8200e-01],
        [9.9994e-01],
        [9.9929e-01],
        [2.8993e-02],
        [9.9160e-05],
        [8.7311e-05],
        [5.4263e-05],
        [9.9998e-01],
        [1.0000e+00],
        [1.5736e-05],
        [3.8971e-04],
        [1.0000e+00],
        [1.0000e+00],
        [7.3184e-05],
        [9.9966e-01],
        [9.9787e-01],
        [7.4348e-04],
        [4.7825e-01],
        [9.9998e-01],
        [9.9977e-01],
        [9.9989e-01],
        [1.0808e-02],
        [1.0000e+00],
        [6.2496e-04],
        [9.9768e-01],
        [1.0000e+00],
        [2.1800e-03],
        [9.9761e-01],
        [1.4539e-03],
        [6.9760e-02],
        [9.9927e-01],
        [8.9053e-01],
        [9.6599e-01],
        [3.1873e-01],
        [1.1253e-01],
        [9.9992e-01],
        [1.0449e-01],
        [6.8256e-01],
        [1.7955e-01],
        [4.1442e-02],
        [9.9997e-01],
        [1.0000e+00],
        [1.6673e-04],
        [1.7982e-02],
        [3.1950e-01],
        [1.0319e-04],
        [4.0960e-05],
        [2.8900e-05],
        [2.8605e-04],
        [1.0638e-01],
        [6.7394e-05],
        [9.9998e-01],
        [1.1582e-02],
        [9.8670e-01],
        [9.1016e-02],
        [1.1133e-04],
        [5.1794e-02],
        [9.9998e-01],
        [1.7318e-01],
        [8.8309e-03],
        [9.9857e-01],
        [2.2302e-02],
        [6.0427e-04],
        [9.5528e-01],
        [3.5384e-03],
        [9.2495e-06],
        [9.6435e-01],
        [2.4974e-03],
        [9.8543e-01],
        [7.7061e-01],
        [5.7808e-05]], grad_fn=<SigmoidBackward0>)

In [194]:
for i in model.model.parameters():
    print(i)

Parameter containing:
tensor([[-0.4034, -0.3353, -0.0566, -0.4176,  0.0713, -0.0378, -0.2689, -0.0986,
         -0.0191,  0.2033, -0.2045, -0.0803, -0.2664, -0.1264,  0.1621,  0.1053,
          0.2676,  0.1856,  0.0482,  0.1469, -0.3048, -0.3033, -0.4532, -0.1297,
         -0.3686, -0.2804, -0.1523, -0.3665, -0.3328,  0.0561],
        [ 0.3270,  0.3618,  0.4872,  0.4085,  0.2670,  0.0275,  0.3407,  0.4684,
         -0.0224, -0.2412,  0.0954, -0.0290,  0.0931,  0.1268,  0.3933, -0.0291,
          0.1735,  0.4075,  0.4411, -0.3190,  0.4155,  0.5655,  0.5161,  0.3993,
          0.6028,  0.0358,  0.2922,  0.4337,  0.4304,  0.0872],
        [-0.4122, -0.5342, -0.2190, -0.2675,  0.0452,  0.2554, -0.4297, -0.4194,
         -0.0935,  0.3035, -0.5271,  0.0521, -0.1427, -0.3617, -0.1572,  0.4780,
          0.0951, -0.0809, -0.0542,  0.4189, -0.4714, -0.8406, -0.3718, -0.5348,
         -0.1998, -0.2925, -0.4292, -0.4917, -0.5416, -0.2059]],
       requires_grad=True)
Parameter containing:
tensor([0.1494, 0.2287, 0.4391], requires_grad=True)
Parameter containing:
tensor([[-0.7559,  1.3293, -1.1558]], requires_grad=True)
Parameter containing:
tensor([0.5091], requires_grad=True)

In [195]:
# Testing
y = model(features_test)
model.loss_function(target_test.reshape(features_test.shape[0],1))

0.12165968120098114

In [196]:
check = []
for i in y.reshape(features_test.shape[0],):
    if i < 0.5:
        check.append(0)
    else:
        check.append(1)

In [197]:
target_test

tensor([0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
        0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
        0., 0., 0., 0., 0., 0.])

In [198]:
z = 0
for i in range(len(target_test)):
    if target_test[i] == check[i]:
        z+=1 
    else:
        print(target_test[i], check[i])
print(z)

tensor(0.) 1
tensor(1.) 0
tensor(0.) 1
tensor(0.) 1
tensor(0.) 1
109

Now we can u se the droput layer and also apply the BatchNormalization in each output of the neuron in each of the hidden layer

Dropout layer is used to dropout or remove/disable certain number of neuron so that the neurons can learn the general pattern through every feature/e=neruon

## Dataset and DataLoaders

In [300]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset, DataLoader

In [301]:
x, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [302]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [303]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [304]:
x = torch.from_numpy(x)
y = torch.from_numpy(y).to(torch.float64)

In [305]:
class CustomDataset(Dataset):

    def __init__(self, features, label):
        # featrue and label
        self.features = features
        self.labels = label

    def __len__(self):
        # return the number of the records in the dataset
        return self.features.shape[0]

    def __getitem__(self, index):
        # return the feature and the label of the index passed
        return (self.features[index], self.labels[index])

In [306]:
dataset = CustomDataset(x, y)

In [307]:
dataset.__len__()

10

In [308]:
feature, label = dataset.__getitem__(2)

In [309]:
feature

tensor([-2.8954,  1.9769], dtype=torch.float64)

In [310]:
label

tensor(0., dtype=torch.float64)

### DataLoader

In [316]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [318]:
for batch_feature, batch_label in dataloader:
    print(batch_feature)
    print(batch_label)

tensor([[-2.8954,  1.9769],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
tensor([[-1.1402, -0.8388],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
tensor([[ 1.0683, -0.9701],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([0., 0.], dtype=torch.float64)