Use the torch.nn module to make the deep learning model easily

In [ ]:
import torch
# nn module
import torch.nn as nn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # the only task of the nn.Lienar is to define a layer of m number of neurons that takes input from n nuerons
        # from previous layers, and perfomrm the linear combination wti the help of the orresponding weight
        self.layer = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.001)
    
    def forward(self, features):
        out = self.layer(features)
        self.y_pred = self.sigmoid(out).to(torch.float64)
        return self.layer.parameters()
    
    def loss_function(self, real_class):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, real_class)
        return self.loss.item()
    
    def optimization(self):
        self.optimizer.zero_grad()
        self.loss.backward()
        self.optimizer.step()
        return {'weights': self.layer.weight, 'bais' : self.layer.bias}

In [ ]:
features = torch.rand(10,5)
print(features)
target = torch.randint(low=0, high= 2, size=(10,1), dtype=torch.float64)
print(target)

tensor([[0.2958, 0.3969, 0.1745, 0.2115, 0.7735],
        [0.4744, 0.3519, 0.3631, 0.2517, 0.5747],
        [0.8698, 0.0729, 0.9253, 0.9887, 0.8151],
        [0.3452, 0.8185, 0.3307, 0.0223, 0.6582],
        [0.3701, 0.3449, 0.9542, 0.7584, 0.9314],
        [0.9889, 0.7138, 0.3512, 0.6811, 0.0341],
        [0.8378, 0.7299, 0.3468, 0.3658, 0.4436],
        [0.9680, 0.9355, 0.6027, 0.2841, 0.3546],
        [0.8493, 0.3864, 0.0573, 0.4634, 0.8894],
        [0.8472, 0.1210, 0.7153, 0.5604, 0.8567]])
tensor([[1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.]], dtype=torch.float64)

In [ ]:
ann = Model(features.shape[1])

In [ ]:
y_pred = ann(features)
y_pred

In [ ]:
ann.layer.weight

Parameter containing:
tensor([[-0.3242, -0.4142, -0.3328,  0.1010,  0.1565]], requires_grad=True)

In [ ]:
ann.layer.bias

Parameter containing:
tensor([0.3196], requires_grad=True)

In [ ]:
loss = 1
for epoch in range(20):
    ann(features)
    loss = ann.loss_function(target)
    print("epoch: ", epoch, "===============>  loss:", loss)
    ann.optimization()

print('weight: ', ann.layer.weight)
print('bias: ', ann.layer.bias)

epoch:  0 ===============>  loss: 0.7006275583113413
epoch:  1 ===============>  loss: 0.7005058790972665
epoch:  2 ===============>  loss: 0.7003843596446699
epoch:  3 ===============>  loss: 0.7002630022969981
epoch:  4 ===============>  loss: 0.7001417758805265
epoch:  5 ===============>  loss: 0.7000207164230015
epoch:  6 ===============>  loss: 0.6998997625787725
epoch:  7 ===============>  loss: 0.6997790122181685
epoch:  8 ===============>  loss: 0.6996583597337582
epoch:  9 ===============>  loss: 0.6995379180817258
epoch:  10 ===============>  loss: 0.6994176091577688
epoch:  11 ===============>  loss: 0.6992974329962891
epoch:  12 ===============>  loss: 0.6991774485970986
epoch:  13 ===============>  loss: 0.6990575648057593
epoch:  14 ===============>  loss: 0.6989378226005468
epoch:  15 ===============>  loss: 0.6988182375593951
epoch:  16 ===============>  loss: 0.6986988394083056
epoch:  17 ===============>  loss: 0.6985795382707278
epoch:  18 ===============>  loss: 0.6984604221122075
epoch:  19 ===============>  loss: 0.6983414488300068
weight:  Parameter containing:
tensor([[-0.3188, -0.4090, -0.3302,  0.1046,  0.1625]], requires_grad=True)
bias:  Parameter containing:
tensor([0.3287], requires_grad=True)

In [ ]:
# ann.layer.parameters() ---> they are the generator so use iteration
for i in ann.layer.parameters():
    print(i)

Parameter containing:
tensor([[-0.3188, -0.4090, -0.3302,  0.1046,  0.1625]], requires_grad=True)
Parameter containing:
tensor([0.3287], requires_grad=True)

In [ ]:
# importing the data as the dataframe from csv file
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
# rempving the unwanted features like id and unnamed: 32
df.drop(columns=['id', "Unnamed: 32"], inplace = True)

In [ ]:
df.shape

(569, 31)

In [ ]:
features = df.iloc[:,1:]
target = df.iloc[:,0]

In [ ]:
# split the data set into train and test
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=43)

In [ ]:
# StandardScaling
scaler = StandardScaler()
# fit_transform will first learn the mean and the s.d. of the trainning data and then do the calculation
# trasnform will that the mean and s.d.of the training data and work for the testing data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
# LabelEncoder
y_train
encoder = LabelEncoder()
y_train_labeled = encoder.fit_transform(y_train)
y_test_labeled = encoder.transform(y_test)

In [ ]:
# as we work on pyTorch, tensor is required for computation
features_train = torch.from_numpy(x_train_scaled).to(torch.float32)
features_test = torch.from_numpy(x_test_scaled).to(torch.float32)
target_train = torch.from_numpy(y_train_labeled).to(torch.float32)
target_test = torch.from_numpy(y_test_labeled).to(torch.float32)

In [ ]:

# making a multi-layer ANN with the overfitting control method dropout and fast convergene method BatchNormalization

class ANN_Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        self.optim = torch.optim.SGD(self.model.parameters(), lr = 0.1)

    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def optimizer(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()

In [ ]:
model = ANN_Model(features_train.shape[1])

In [ ]:
for i in model.model.named_parameters():
    print(i)

('0.weight', Parameter containing:
tensor([[-0.0325, -0.0940,  0.0777, -0.1268, -0.1701, -0.1682,  0.1756, -0.1106,
         -0.0243,  0.0165, -0.1670, -0.0082, -0.1068,  0.0552,  0.0096, -0.1600,
          0.0077, -0.1108,  0.1230,  0.1796,  0.1439,  0.1653,  0.1331, -0.0109,
          0.1229,  0.1636, -0.1218,  0.0484,  0.0482,  0.0361],
        [ 0.1164, -0.0153,  0.0650, -0.1276,  0.1757,  0.1502,  0.0173, -0.1735,
          0.1707, -0.0078, -0.0495,  0.1670, -0.0046, -0.1574,  0.1649,  0.1448,
         -0.0857, -0.1436,  0.1159, -0.1785,  0.1642,  0.0488, -0.0181, -0.1579,
         -0.0791,  0.1488, -0.0574, -0.1350,  0.0422, -0.1176],
        [-0.0396,  0.1051,  0.0498, -0.0910,  0.0214, -0.1050,  0.0929, -0.1458,
         -0.1222, -0.0491, -0.1476,  0.1769, -0.1170, -0.0234,  0.0565,  0.1646,
         -0.0275, -0.0832, -0.0752, -0.0697, -0.0408,  0.0518, -0.0944,  0.1568,
         -0.1064, -0.0731,  0.1556, -0.0430, -0.0465,  0.0763]],
       requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.1123,  0.1556, -0.0070], requires_grad=True))
('2.weight', Parameter containing:
tensor([[-0.1147,  0.2938,  0.0985]], requires_grad=True))
('2.bias', Parameter containing:
tensor([0.5546], requires_grad=True))

In [ ]:
epoch = 20

In [ ]:
# training for 20 epochs
for i in range(30):
    print(i)
    model.forward(features_train)
    model.loss_function(target_train.reshape(features_train.shape[0],1))
    model.optimizer()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29

In [ ]:
for i in model.model.parameters():
    print(i)

Parameter containing:
tensor([[-0.3214, -0.4070, -0.2105, -0.4135, -0.2168, -0.2886, -0.0813, -0.3853,
         -0.0871,  0.1104, -0.3950,  0.0257, -0.3096, -0.1710,  0.0847, -0.1316,
         -0.0214, -0.1314,  0.1779,  0.2487, -0.2156, -0.2087, -0.2141, -0.3500,
         -0.0996, -0.0281, -0.4017, -0.2687, -0.2177, -0.1056],
        [ 0.4202,  0.2790,  0.3621,  0.1563,  0.2405,  0.1969,  0.2557,  0.1045,
          0.1423, -0.2094,  0.1164,  0.0417,  0.1281,  0.0152,  0.0945,  0.0545,
         -0.0252, -0.0545, -0.0237, -0.2923,  0.5223,  0.3994,  0.3272,  0.1628,
          0.1932,  0.2958,  0.2472,  0.2350,  0.2718, -0.0184],
        [-0.0847,  0.0651,  0.0069, -0.1339, -0.0029, -0.1009,  0.0722, -0.1829,
         -0.1303, -0.0128, -0.1862,  0.1833, -0.1465, -0.0583,  0.0579,  0.2042,
         -0.0022, -0.0752, -0.0592, -0.0277, -0.0952, -0.0023, -0.1440,  0.1075,
         -0.1519, -0.0751,  0.1328, -0.0836, -0.0806,  0.0825]],
       requires_grad=True)
Parameter containing:
tensor([0.4021, 0.4445, 0.0468], requires_grad=True)
Parameter containing:
tensor([[-1.2388,  1.2117, -0.2788]], requires_grad=True)
Parameter containing:
tensor([-0.3332], requires_grad=True)

In [ ]:
# Testing
y = model(features_test)
model.loss_function(target_test.reshape(features_test.shape[0],1))

0.10989295691251755